urls = [
    "site:listicleclothing.* Wide Strap Sweater Knit Brami Top",
    "site:noenddenim.* Claude Crop High Rise Straight Jeans",
    "site:heavenmayhem.* KISS",
    "site:noenddenim.* Claude High Rise Straight Crop Jeans",
    "site:firebirdkids.* Cotton Cashmere Unisex Hoodie",
    "site:princesspolly.* Rehna Long Sleeve Top White",
    "site:walooproducts.* Carbon Fiber Silicone Band",
    "site:shopwearwell.* The Brisa - Wide",
    "site:callowaymills.* Black Border Monogram Doormat | Letter S",
    "site:lonarc.* Bali One Piece Black and Nude Strips, Additional Black Straps",
    "site:petlife.* Anti-Slip Rubberized Gripped Breathable Stretch Pet Dog Socks - Set of 4",
    "site:findmenowthelabel.* Floral Lace Flutter Sleeve Top",
    "site:vidalite.* LED Glass Globe Pendant Light",
    "site:getcasely.* Love Song | Lavender Heart Case - Bold + MagSafe¬Æ",
    "site:luvprismcosmetics.* Faux Luxe Mink Lashes LP10",
    "site:agolde.* Lana Mid Rise Straight in Sway",
    "site:napahomeandgarden.* Burma Rattan Serving Bowl ",
    "site:fifthandninth.* Dallas",
    "site:parkerbaby.* Felt Laundry Hamper",
    "site:blueagejeans.* Women's Denim Jacket With Distressed",
    "site:alalastyle.* Phoebe Mock Knit",
    "site:babyktan.* GiftSet: Arizona Baby Muslin Swaddle Blanket and Burp Cloth/Bib Combo",
    "site:sassywoof.* Dog Bundle - Cuddly Corgis - Small Collar",
    "site:shopvustra.* Poseidon Polo",
    "site:simplerhaircolor.* Shampoo",
    "site:nidecker.* Supermatic Snowboard Bindings 2024",
    "site:sanlorenzohawaii.* Bikini Adapta Cocoa Bean",
    "site:benbenapparel.* Womens 2 Pack Joggers Super Soft",
    "site:yomtovsettings.* 8 In. Classic Green Design Plastic Plates | 120 Count",
    "site:portlandgear.* Corduroy CB Dad Hat - Black",
    "site:jupitergear.* PBLX Resistance Trainer Platinum 45 Lbs",
    "site:luminesscosmetics.* Breeze2 Airbrush Makeup & Skincare System Kit",
    "site:karmagifts.* Catalina Short Tumblers",
    "site:princesspolly.* Mercer Linen Blend Maxi Skirt",
    "site:lola-jeans.* Gabriella-CSN Classic Denim Jacket",
    "site:avenuezoe.* Yoga Cargo Shorts",
    "site:elianamaternity.* Striped Side-Button Maternity & Nursing Long Sleeve Top - Lightweight Maternity Tops for Work - Shirt & Blouse Office Wear",
    "site:foreverylivingthing.* SANTA MONICA CHINO SHORTS",
    "site:yelete.* Womens Seamless Triple Criss-Cross Front Cami",
    "site:instagram.* RFM Crop Chloe Full Size Tummy Control High Waist Raw Hem Jeans",
    "site:vibrantmiu.* A Miss Wide Jeans",
    "site:stuhrling.* Ultima 3960 Quartz 42mm Chronograph",
    "site:ccs.* Original Relaxed Corduroy Pants - Inseam 32",
    "site:elunausa.* Stripe Camo Twist Bottom Top",
    "site:napahomeandgarden.* Leafy Vine Prints, Set Of 4",
    "site:theloomia.* Nur Accent Arm and Lounge Chair Set of 2",
    "site:findmenowthelabel.* Harmony Checkered Mesh Top",
    "site:helena-quinn.* Sheer Dark Floral Robe",
    "site:worldmoderndesign.* Easter Egg Chair",
    "site:glamcor.* ELITE X - LIGHT ONLY",
    "site:shopdirectdeals.* Tension Curtain Rod Spring Load Adjustable Curtain Pole Heavy-Duty Steel 4 Sizes",
    "site:michaellaurenclothing.* Brauner Halter Tube Top ",
    "site:getcasely.* Miracle Ticket | Grateful Dead Vintage Case - Bold + MagSafe¬Æ",
    "site:instagram.* Luxe Long Basic Ink",
    "site:dormify.* Printed Leopard Duvet and Sham Set",
    "site:speckproducts.* Presidio2 Grip MagSafe with ClickLock iPhone 15 Pro Cases",
    "site:explorercoldbrew.* 32oz Cold Brew",
    "site:tigerpetmarket.* Venison Sausage Treat Chews for Dog",
    "site:shopdrt.* Robert Fitted Blazer",
    "site:korkers.* OmniTrax v3.0 - Kling-On Sticky Rubber Soles",
    "site:drinkmonday.* MONDAY Zero Alcohol Whiskey",
    "site:edikted.* Alice Gathered Waist Shorts",
    "site:parcilsafety.* IIR-100 Recon Tactical Gas Mask",
    "site:lumberlegs.* Butterfly (Light) - Inseam 4",
    "site:izzo.* Splash Out Bunker Training Aid",
    "site:explorercoldbrew.* Coffee & Flavor Bundle - Vanilla & Caramel",
    "site:bartonwatchbands.* Apple Watch Dark Brown Pittards Performance Leather Brown Stitching Watch Band",
    "site:getcasely.* Spot On | Dotted Animal Print Case - Classic",
    "site:ruggable.* Jonathan Adler Inkdrop Black & Ivory Tufted Round Rug + Pad System",
    "site:harmonify.* Mosaic Candle Holder ‚Äì Red Handmade Colorful Glass Tealight Candle Holder",
    "site:shopatlasgrey.* Zodiac Crewneck | Scorpio",
    "site:polychromegoods.* Butter Embroidered Courduroy Hat",
    "site:sohosocial.* Kaya Double Strap Nylon Crop",
    "site:littletrouble.* Wild One T-Shirt",
    "site:huntedfox.* Stone Washed Light Grey Pillow",
    "site:gernienyc.* 26's Laceless Low Top",
    "site:marketstudios.* SMILEY 6 FOOT MONOCHROME RUG",
    "site:one33social.* The Isabelle | Fuchsia V-Neck Slip Gown",
    "site:solincosports.* Blackout 265 Racquet Unstrung",
    "site:residence.* Distant Paradise",
    "site:uswe.* Bladder",
    "site:thecaep.* Nelson IPhone Case - MagSafe",
    "site:ragnco.* Fairleigh Strappy Slip on Sandals",
    "site:btiff.* RG093MG B.Tiff 2 Ct Moissanite Round Gold Solitaire Engagement Ring",
    "site:ninexisusa.* Full Size Quarter-Button Collared Sweatshirt",
    "site:princesspolly.* Rehna Halter Top  ",
    "site:jonathany.* Salines Diamond Trellis Indoor/outdoor Area Rug - Rectangle",
    "site:babyjogger.* City Mini¬Æ Gt2 Double Stroller",
    "site:hellyhansen.* Women's Alphelia Lifaloft Jacket",
    "site:kodakphotopl.* KODAK Projection Screen 80 with Tripod Stand & Carrying Bag",
    "site:ruggable.* Adeline Dark Wood Rug + Rug Cover",
    "site:weegallery.* Tummy Time Gift Set for Baby - Jungle Animals",
    "site:popsockets.* PopSockets PopGrip Dreamy Galaxy Swirl",
    "site:noenddenim.* Eve Slim Straight Crop Jeans",
    "site:femmessanspeur.* MAYA SCOOP BACK PINK TROPICAL SWIMSUIT",
    "site:agolde.* Daryl Pant in Basket",
    "site:designdua.* Signature Bilia Bassinet: Natural",
    "site:princesspolly.* Wurli Mini Dress",
    "site:diono.* Cambria¬Æ 2 Latch 2-in-1 Booster Car Seat",
    "site:avenuezoe.* Tassel Open Hoop Earrings",
    "site:jnlnaturals.* Aluminum-Free Deodorant (Duo) - Peppermint & Bergamot",
    "site:sandcloud.* Set Stripe Beige",
    "site:arborcollective.* Satori Camber Splitboard 2024",
    "site:trueclassic.* Carbon Boxer Trunks 12-Pack",
    "site:8otherreasons.* SHAMELESS RING",
    "site:roshambo.* Blippi Shades | Toddler | Blippi Orange Frame",
    "site:lamielclothing.* Crew Neck Stripe Short Sleeve Top",
    "site:blomus.* Ceramic Stoneware Plates Set of 4 - SABLO",
    "site:jambys.* House Hoodie",
    "site:magnlens.* Essential 8 Sweat Shorts",
    "site:urban-classics.* Men's Essential Fade Tee",
    "site:farbank.* Rio Brammer Finger Mullet Fly",
    "site:fashiongo.* Notch Neck Rib-Knit Crop Top",
    "site:rmjewelrync.* Solid 925 Sterling Silver Figaro Chain Necklace 4mm",
    "site:rellery.* Checker Rings - Blue Set of 2",
    "site:coleman.* Kompact Premium Inflatable Camp Sleeping Pad",
    "site:globalcutleryusa.* 11 Forged Chef's Knife",
    "site:emandlivjewels.* The √âcart√© Ring",
    "site:littletrouble.* Stay Fast Hoodie",
    "site:marigoldshadows.* Yuzuki Vegan Leather Face Mask - Grey",
    "site:youngdays.* Eco-Friendly, 100% Organic Cotton Tee (Azores Tee)",
    "site:laurengadams.* Layers of Love Stackable Ring RS69951BCLEAR",
    "site:gbrunostore.* Double Dogs Leash No-Tangle W/ Swivel Coupler Padded Handle",
    "site:threadedpear.* cRAZY sockS for MeN ",
    "site:xixpalms.* Bogota Party Dress",
    "site:cgklinens.* 4 Piece Sheet Set",
    "site:bobore.* Rebecca Small Cutie Leather Bag",
    "site:princesspolly.* Anysa Mini Dress",
    "site:heritagesteel.* Large Skillet With Steamer Insert, Dome Lid, and Flat Lid - Clearance",
    "site:scientificanglers.* Wetcel General Purpose Type VI Fly Line",
    "site:organicbasics.* Core Trunks 3-Pack",
    "site:artorama.* Van Gogh - The Starry Night, 1889 Artwork Poster - Matte",
    "site:crunch-n.* Honey Bits Freeze Dried Candy",
    "site:westernrise.* Transit Overshirt",
    "site:jnlnaturals.* Razor Set",
    "site:easy-clothes.* Green Marina Sweater",
    "site:billyreid.* ASTOR COAT",
    "site:jmpthelabel.* Vegas Bandeau Bikini Top - Wanderlust",
    "site:sassywoof.* Cat Bundle - Zest Friends | SMALL COLLAR",
    "site:shopatkon.* Konus Men's Elongated Button Up Shirt ",
    "site:letocollection.* Contour Rib Knit Brami Lounge Top",
    "site:sheepskin.* LADIES DUO-TONE EMMA SHEEPSKIN SLIPPER",
    "site:edikted.* Karter Metallic Halter Top",
    "site:coneyislandpicnic.* Grow with Us Printed Midi Skirt",
    "site:dameliofootwear.* Nyra Sandal - Silver",
    "site:beverlyrug.* Washable Non-Slip Love Area Rug Multicolor Happily",
    "site:arvowear.* Arvo Clear Gem Bracelet",
    "site:karmagifts.* Leather Leaping Deer Ornament",
    "site:bigjigstoys.* Picnic Bench",
    "site:edikted.* Joey Oversized Jacket",
    "site:gbrunostore.* 8Pcs Baby Nappy Diaper Bags Set",
    "site:callowaymills.* Hanukkah Greetings Doormat",
    "site:lamielclothing.* Peyton Jacket",
    "site:casafinagifts.* Casafina Fontana White 5-Piece Place Setting",
    "site:forme.* Revive Bra",
    "site:choosemuse.* Muse S (Gen 2)",
    "site:somethingglitter.* 1 4/5 CT DEW Created Moissanite-White Fashion Ring 10k Gold",
    "site:shopraga.* Deema Midi Dress",
    "site:sivanaspirit.* Alessandra Skirt - Medium and Large Only",
    "site:daniel-patrick.* USA Surplus Crewneck",
    "site:fang.* Pointelle Loop Top",
    "site:xixpalms.* Santa Maria Party Dress",
    "site:rta.* SINGLE BREASTED BLAZER | DUSTY BLUE",
    "site:claudiagcollection.* Leaf Bracelet",
    "site:ettitude.* Sateen Shorts",
    "site:ellamila.* The ELITE Collection",
    "site:shun.* Combination Honing Steel",
    "site:shopdirectdeals.* 4-Pack Reusable Nonstick Stovetop Burner Protector Liner",
    "site:sortjoy.* The Flex Bin - Original",
    "site:portolano.* NAPPA GLOVE WITH BUCKLE",
    "site:areohome.* Brass Bell - Sm - Brass",
    "site:1people.* Cap Ferret XAC - Long Sleeves Shirt - Sommerhus",
    "site:sundayswagger.* Cowabunga - Men's",
    "site:lola-jeans.* Alexa-CSN High-Rise Skinny Jeans",
    "site:surfsidesupply.* Brian Slub Shirt - Strong Blue",
    "site:zwilling.* ZWILLING Motion Nonstick Hard-Anodized Cookware Set",
    "site:fashiongo.* High Rise Ripped Frayed Hem Straight Jeans",
    "site:rootine.* Rootine Focus Aid | Adaptogen Drink Mix for Better Focus | CDP-Choline, Uridine, Panax Ginseng, Bacopa Monnieri, Natural Caffeine from green coffee bean | Drug-Free, Non-Habit Forming, Made in USA",
    "site:shopatkon.* Women's Grid Print Blouse in Navy Plaid",
    "site:babyktan.* Arkansas Pine Baby Onesie",
    "site:lashnextdoor.* Put To The Test Tank",
    "site:getcasely.* Field of Flowers | Pastel Floral Samsung Case",
    "site:ghostgolf.* GOOD BOGEY SNAPBACK",
    "site:tikipets.* Tiki Cat Grain-Free Aloha Friends Tuna With Pumpkin Wet Cat Food in Pouches - 3 Oz Pouches ",
    "site:lithiumautocare.* ForeClay Bars",
    "site:anna-kaci.* Solid Color Ruffle Strap Dress",
    "site:mistymountaingaming.* The Mad Scientist Aluminum Metal Dice Set",
    "site:princesspolly.* Cynthia Dress",
    "site:stephenjosephgifts.* Super Soft Plush Dolls",
    "site:getcasely.* The Valentine's Collection | Galaxy Right Heart Case | Essential",
    "site:fuzzycove.* Premium Felted Wool Cat Cave Bed - Cozy Peekaboo Round Cave",
    "site:weiv.* Raw Cut Sweat Shorts",
    "site:youngdays.* Taos Henley",
    "site:mnml.* Knee Distressed Ultra Baggy Denim - Black",
    "site:bartonwatchbands.* Withings Nokia Activite And Steel Hr Tropical Style Smoke Grey Watch Band",
    "site:somethingglitter.* Silver white 58mm round wave Hoop Earrings 2.5mm thick",
    "site:en-masse.* TRIBAL KEYCHAIN",
    "site:getcasely.* Midnight Color Splash | Abstract Retro Google Pixel Case",
    "site:zulaykitchen.* Stemless Wine Glasses Set",
    "site:lincove.* Lincove Luxury Down Alternative Pillows - Premium Hotel Collection for Back and Side Sleepers, Neck Support, Fluffy Comfort , Standard - 2 Pack",
    "site:farmina.* N&D Prime Ocean Herring & Orange Mini Adult Dry Dog Food - 5.5 Lb Bag",
    "site:polychromegoods.* I want you to SPF me Embroidered Hat",
    "site:terramarsports.* Women's 2.0 Thermapeak Heritage Midweight Thermal Pants",
    "site:princesspolly.* Lukea Long Sleeve Mini Dress",
    "site:instagram.* Striped Button Front Cardigan",
    "site:shopvustra.* Driftwood Polo",
    "site:laticoleathers.* Deja Crossbody",
    "site:hadleydesigns.* Gold Baby Shower Word Scramble & True or False Game",
    "site:loveprayjewelry.* Red Tiger's Eye Gemstone 27 Bead Mala Bracelet With Tree of Life Charm",
    "site:judybluejeans.* Judy Blue Full Size Taylor High Waist Overalls",
    "site:becketandquill.* Single Stone Band",
    "site:shopbrabar.* Everyday Baselayer Bandeau Bra",
    "site:avenuezoe.* Mini Ball Bearing Charms Necklace",
    "site:jennywulace.* Mobius Steel Ring - Light",
    "site:petersonhousewares.* 7 Touch Lamp-Fragrance Wax Melts Warmer-Electric Essential Oil Burner",
    "site:helloyumi.* Silicone Baby Bib",
    "site:malbongolf.* ANOUK DRESS",
    "site:frenchkyss.* Knit Tank",
    "site:lonarc.* Alamo One Piece",
    "site:rockandrollcandleco.* 'Rock & Roll' Reed Diffuser",
    "site:gurunanda.* Dual-Line Floss Picks",
    "site:essellesf.* Foldable Vegan Leather Basket",
    "site:featclothing.* Mens BlanketBlend Move Short",
    "site:callawaygolf.* Men's Performance Front Crested Unstructured Hat",
    "site:fashiongo.* HERE for the FIREWORKS GRAPHIC TEE",
    "site:princesspolly.* Giorgi Lace Corset",
    "site:princesspolly.* Zamora Midi Dress Champagne",
    "site:nanajudy.* NM10013E MONTANA HOOD",
    "site:princesspolly.* Millbank Top White",
    "site:thousandfell.* Handmade Vegan Sneaker | Women's Court | Retro Grey-Baby Blue",
    "site:princesspolly.* Kyro Mini Dress",
    "site:ccs.* Original Relaxed Corduroy Pants - 30 Inseam",
    "site:gfpet.* Retro Puffer ",
    "site:agolde.* Low Slung Baggy 30.5 in Pink Salt",
    "site:getcasely.* Cotton Candy | Blue & Purple Marble Case - Classic",
    "site:emilehenryusa.* Sublime Braiser 4 QT",
    "site:nylora.* NAOMI MESH COMBO SKIRT BLACK",
    "site:broilkingbbq.* Select PVC Polyester Grill Cover for Baron and Crown 500 Pellet Grill",
    "site:getbullish.* A Different Breed of Mama Bear Unisex Jersey Short Sleeve Tee",
    "site:beverlyrug.* Laguna Dark Blue Bordered Indoor Area Rug",
    "site:revlon.* COLORSTAY SKIN AWAKEN CONCEALER",
    "site:fratelliguzzini.* Dolcevita Bowl",
    "site:bhufoods.* Mint Chocolate Lover's Bundle",
    "site:bluebuffalo.* Blue Buffalo Chicken and Brown Rice Mature Adult Dry Cat Food - 3 Lbs",
    "site:4artworks.* Wow Emoji",
    "site:mujjo.* CANOPY AIRTAG KEYCHAIN",
    "site:doucce.* Cach√© Cr√®me Concealer",
    "site:shopatlasgrey.* Organic Chunky Knit Sweater",
    "site:amyandannette.* Sterling Silver Oxidized Flower Band",
    "site:fashiongo.*  Make America Cowboy Again Graphic Tee",
    "site:stephenjosephgifts.* Quilted Purse",
    "site:trilipiderm.* Limited Edition Essential Oil Infused Hydrating Exfoliant Cleanser",
    "site:sendaathletics.* Women's Ushuaia Pro 2.0 Futsal Shoe",
    "site:evercado.* Fleece Cropped Sweatshirt",
    "site:elyontableware.* Ramapo 2-Piece Reflective Hand-Forged Cheese Knife Set High Quality Stainless Steel",
    "site:gathre.* Padded Midi Circle",
    "site:anna-kaci.* Workout Shorts Athletic Sports Running Shorts Active Yoga Gym Sport Shorts",
    "site:tinilux.* Bijou Gold Stud Earrings",
    "site:bossnationbrands.* Boss Dog Tactical Patch for Harnesses",
    "site:toastedjewelry.* Opal Teardrop Hoops",
    "site:shopwearwell.* The Elena - Wide",
    "site:fukapi.* Ermont Hoodie - Cloud",
    "site:ifthenwell.* Premium Peruvian Pima Cotton Short Sleeve T-Shirt | Purple",
    "site:maralabel.* Mocha Linen Almafi Set",
    "site:lillarose.* Elastic Strap - Nickel Plating",
    "site:rags.* Short Sleeve Henley Rag Romper",
    "site:ramgolf.* Ram Men's Golf Player Waterproof Golf Shoes",
    "site:getcasely.* Yellow Submarine | Beatles Case - Bold+MagSafe¬Æ",
    "site:loveandfit.* SoftLuxe Crop Top - Dark Heather Grey",
    "site:headandshoulders.* Mens Full & Thick 2 In 1 Dandruff Shampoo And Conditioner | 4 Pack",
    "site:karmagifts.* Thin Headbands",
    "site:bayeas.* UTILITY PATCH POCKET WIDE LEG JEANS",
    "site:toastedjewelry.* Hammered Horizontal Bar Ring",
    "site:mnml.* B469 Flare Denim - Blue",
    "site:sheswaisted.* PowerMesh X Panel High-Waist Shorts",
    "site:yearandday.* The Infinite Candle",
    "site:ragcompany.* Big Treat Rhinestone Embellished Lace Up Sandals",
    "site:tomorrowslaundry.* Classic Essential Tee",
    "site:princesspolly.* Donelli Lace Mini Dress",
    "site:hugglehounds.* Adoption Pack (Small Pup Size)",
    "site:shopnocturne.* Off-Shoulder Dress",
    "site:princesspolly.* Athina Romper",
    "site:ragnco.* Beroe Braided Handcrafted Lace Up Sandal",
    "site:serenehouseusa.* Sleep CBD Roll-on 10ml",
    "site:gathre.* Tablecloth",
    "site:bandai.* Mobile Suit Gundam G Frame FA 01 Freedom Gundam",
    "site:malbongolf.* TILDA SHORTS",
    "site:karmagifts.* Holiday Chic Stemless Wine Glasses",
    "site:coddies.* Brook Trout Flops",
    "site:getcasely.* The Valentine's Collection | Love Doodles Case - Essential + MagSafe¬Æ",
    "site:sassywoof.* Dog Adjustable Harness - Disney's Ariel",
    "site:poisepup.* COLLAR",
    "site:arvowear.* Arvo Time Squared Watch - Black Dial",
    "site:princesspolly.* Yui Top",
    "site:adinaeden.* Lined Polished X Ribbed Heart Stud Earring",
    "site:edyson.* Peter Utility Jacket",
    "site:chadocosmetics.* Skin Perfector - Cream",
    "site:hotelcollection.* Sakura - Regular",
    "site:jambys.* SoftStretch Basketball Shorts",
    "site:degsandsal.* Sterling Silver Skull Bead Bracelet",
    "site:thelickerstore.* Koko Cat Scratcher - Modern Cardboard, Non-Toxic, Durable - Clever Design for Small Spaces",
    "site:corkcicle.* The Matrix Sport Canteen ",
    "site:mauiandsons.* Ten Thousand Reversible Bucket Hat",
    "site:bigjigstoys.* Sweetland Express",
    "site:hyfve.* Treat Me Right Sleeveless Ruffled Romper",
    "site:swingjuice.* Golf Maryjane Men's Polo",
    "site:judybluejeans.* Full Size Distressed Raw Hem Bootcut Jeans",
    "site:basicbae.* Bamboo Full Size Round Neck Short Sleeve T-Shirt",
    "site:mysmileteeth.* Essential Sonic Toothbrush",
    "site:cloutcoffee.* Rum Barrel Aged - Whole Bean Light Roast",
    "site:glowhub.* Nourish & Hydrate Body Serum",
    "site:jiggypuzzles.* 450 Piece Puzzle and Frame Bundle  - Black Frame",
    "site:lovenala.* Mackeral Carrot and Pumpkin Pate Canned Cat Food - 2.8 Oz",
    "site:arborcollective.* Westmark Camber Frank April Edition Snowboard 2024",
    "site:rta.* NOA TOP | BLACK",
    "site:princesspolly.* Aubriella Lace Mini Dress",
    "site:nuxactive.* Shoulder Holder Crop",
    "site:julielindh.* Infrared Sheet Mask in Hyaluronic Acid and Rose Serum",
    "site:waagbag.* Star Gazer Dog Necklace",
    "site:sijohome.* LuxeWeave Linen Sheet Set",
    "site:fashiongo.* Mammoth Lakes California Oversized Graphic Tee",
    "site:jackieaslick.* Jacki Easlick Three Chickens Sandals - Men's",
    "site:ruggable.* Alessia Dark Wood Tufted Round Rug",
    "site:rellery.* Matte Silver Men's Wedding Ring",
    "site:shopatkon.* Women's Long Sleeve Turtle Neck Fitted Top",
    "site:princesspolly.* Paradis Mini Dress",
    "site:loomini.* Classic Backpack 17 Fuchsia",
    "site:untuckit.* Imogen",
    "site:instagram.* White Skinny Jeans",
    "site:acemarks.* Chukka Boot Brown Antique",
    "site:shopwearwell.* The Moccasin - Very Wide",
    "site:winnielou.* Crisps & Jerky Bundle",
    "site:hellonoemie.* The Bohemian Dancer Ring",
    "site:lonarc.* Amatista One Piece Black and Nude Stripes - XXL",
    "site:sanlorenzohawaii.* ANIMAL Jungle Cat Design V-Cut Thin Brief Bikini Bottom",
    "site:feltandfat.* Share Bowl in Slate",
    "site:sassywoof.* Dog Rope Leash",
    "site:yourcatbackpack.* The Day Tripper Perfect Adjustable H-Style Cat Harness & Bungee Leash Set - Color Block",
    "site:elmandrye.* Apple Cider Vinegar - Gummies",
    "site:loveprayjewelry.* Healing and Change, Sandalwood and African Turquoise 27 Beads Unisex Mala Bracelet",
    "site:beverlyrug.* Washable Non-Slip Paintings Area Rug Blue Night",
    "site:sandcloud.* Make the Sea Trash Free Kids Tee - White",
    "site:lovoda.* Bon Bon Bracelet",
    "site:objectshq.* Zagarise Hand Tufted Wool & Viscose Rug",
    "site:ds.* Green Abstract Print Smock Waist Casual Shorts",
    "site:multitasky.* PhonePal 3 in 1 PRO: Cooling Fan + Power Bank + Phone Stand (With Display Panel) ",
    "site:weiv.* Weiv Mens Print Hawaiian Button Down Shirt",
    "site:pumagolf.* Men's Ignite Elevate Wide Golf Shoes",
    "site:sohosocial.* Millie Sequin Zebra Tube",
    "site:claudiagcollection.* Beehive Planter",
    "site:daniel-patrick.* Chelsea Roamer",
    "site:knotwtr.* Knotwtr B&W Low Top Shoes",
    "site:aweinspired.* The Morrigan Necklace - Long 20-22",
    "site:edikted.* Jordan V Neck Halter Top",
    "site:petlife.* Active 'Downward Dog' 4-Way-Stretch Fitness Yoga Dog Tracksuit Hoodie",
    "site:bakkenswiss.* Bakken- 13-Inch Perforated Pizza Crisper Carbon Steel Pizza Pan",
    "site:momeni.* Baja - 3",
    "site:ezpzfun.* Mealtime Plate (2-Pack)",
    "site:edyson.* Valentino High Rise Wide Leg Jeans",
    "site:shopatlasgrey.* Organic Chunky Knit Sweater",
    "site:btiff.* RG111G B.Tiff Gold Stacking .01 Ct Eternity Ring [Thin Band]",
    "site:sijohome.* FineSlumber Nightdress",
    "site:princesspolly.* Allise Frill Top Cream",
    "site:orvis.* Mirage LT Fly Reels",
    "site:yomtovsettings.* 8 In. Silver Scratched Design Plastic Plates | 40 Count",
    "site:jonathany.* Marcel Globe Farmhouse Modern Iron Bistro LED Semi Flush Mount",
    "site:ferastyle.* Kate Parka",
    "site:keababies.* Jumbo Toddler Pillow with Pillowcase",
    "site:heiressbeverlyhills.* Black Stretch Knit Open-Back Belted Maxi Dress",
    "site:shopatkon.* Konus Men's SS Nightcall Graphic Tee in Black",
    "site:everplush.* Memory Foam Herringbone Accent Rug",
    "site:getcasely.* Half Moon High Contrast Design Case - Essential",
    "site:shopatkon.* Men's Tonal Checkered Shorts With Tape",
    "site:edikted.* Shlo Knitted Cardigan",
    "site:daniel-patrick.* Venice Trunk",
    "site:makersshoes.* HANNAH",
    "site:misen.* Silicone Tongs",
    "site:capellaapparel.* Solid Ribbed Slit Neckline Sleeveless Romper",
    "site:shopatkon.* Men's Wide Print Patch French Terry Sweatpants",
    "site:frenchiebulldog.* Frenchie Duo Reversible Harness - Lemon Tree",
    "site:rebecca-allen.* The Loafer, Nude II",
    "site:callowaymills.* Hummingbird Welcome Doormat",
    "site:ezpzfun.* BapronBaby¬Æ Bapron",
    "site:princesspolly.* Francia Frill Top",
    "site:joypaperco.* Happy Fall Y'all Card",
    "site:buyhi.* Vanilla Protein",
    "site:shopwearwell.* The Camila - Wide",
    "site:snagtights.* Love Me - Red",
    "site:gothamsteelstore.* Natural Collection 15-Piece Set",
    "site:emprella.* 2 Pack High Waist Yoga Running Compression Biker Shorts for Workouts Exercise with 3 Pockets",
    "site:powerurfun.* 27pc Pop Puzzle Popper Fidget Game",
    "site:sunnydaycase.* Virtual Vocalist Miku Plant-Based Phone Case",
    "site:peopleofleisure.* Guns N Roses Appetite For Destruction Shrunken Tee",
    "site:zalousa.* Unicorn Set Suction Massager",
    "site:cgklinens.* Premium Down Alternative Comforter",
    "site:luxclub.* LuxClub 6 PC King Sheet Set, Breathable Luxury Bed Sheets, Deep Pockets 18 Wrinkle Free Cooling Bed Sheets Machine Washable Hotel Bedding Silky Soft - Yellow King",
    "site:fashiongo.* Tie-Dye Seamless High Waisted Leggings",
    "site:purecosmetics.* Hydrating, Natural, Moisturizing, Medical-grade Lanolin Led Light & Mirror - neutral pink",
    "site:nutrisourcepetfoods.* Grain-Free Turkey and Turkey Liver Canned Cat Food",
    "site:bakedcravings.* Red Velvet Cake in a Cup",
    "site:futurekind.* Vegan Collagen Booster Biotin Gummies",
    "site:adinaeden.* Indented Open Hoop Earring",
    "site:kimtrue.* Scalp Clear Gel (Vitality)",
    "site:sabavihome.* Lucite Utensils Caddy",
    "site:vongernhome.* Round Reversible Metallic Placemat",
    "site:wearethewildco.* Dallas Cowboys Women's Metallic Track Jacket",
    "site:tossware.* RESERVE 9oz Stemless Champagne",
    "site:unlesscollective.* Jogger Pant",
    "site:princesspolly.* Rios One Shoulder Top",
    "site:robertovino.* The one T-shirt",
    "site:hausandhues.* Purple queen of hearts (unframed)",
    "site:earthbrands.* Earth Hoodies",
    "site:drowsysleepco.* DROWSY Eyelash Protecting Silk Sleep Mask. Face-Hugging, Padded Silk Cocoon for Luxury Sleep in Total Darkness.( Moonlight Shadow)",
    "site:movophoto.* LV2 | Double-Lav Omnidirectional Interview Mic ",
    "site:organicbasics.* True Knit Sweater",
    "site:mauiandsons.* Beachbreak T-Shirt",
    "site:stephenjosephgifts.* Insulated Food Jar",
    "site:bayleenasco.* Baby Blue Bagel Bed",
    "site:callowaymills.* This Is the Dogs House We Just Live Here Doormat",
    "site:swingjuice.* Golf Retro Rhythmic Lines Unisex Snapback Hat",
    "site:cleandesignhome.* Cotton 2-Pack Hand Towel",
    "site:sivanaspirit.* Bamboo Palazzo Pants",
    "site:sortjoy.* The Sculpted Bin - Wide | Set of 3",
    "site:vervetdenim.* Mid-Rise Straight Crop Jeans",
    "site:princesspolly.* Hagner Long Sleeve Top ",
    "site:mahoshades.* Chandeleur Whisky",
    "site:scientificanglers.* Hard Mono Tippet",
    "site:hausandhues.* Red edgy (unframed)",
    "site:bigagnes.* Gold Camp 5 Tarp",
    "site:candidaura.* The Time Is Now Baseball Cap",
    "site:twillory.* Performance Blazer // NAVY PLUM CONTRAST // Long",
    "site:izakov.* Small 14K Gold Rounded Oval Cable Link Necklace",
    "site:threesixty6.* Men's Dry-Fit Long Sleeve Golf Polo Shirt",
    "site:pjharlow.* Mikel Satin Boxer Short With Draw String",
    "site:haakwear.* Knit Cuffed Beanie, Made in USA",
    "site:surfsidesupply.* Tide UPF 50 Sleeve Quick Dry Hoodie - Sky Blue",
    "site:ascom.* Asus MQ13AH 13 Class Full HD OLED Monitor",
    "site:pinkpickleboutique.* Pickleball Era - Women's Long Sleeve",
    "site:whitebirchusa.* Floral Print Halter Woven Dress",
    "site:kendallconraddesign.* THICK ROUNDED RING",
    "site:lashowroom.* Retro Multi Lightning Graphic Tee",
    "site:kellyrosegold.* 14k White Gold Anklet With Fancy Hammered Oval Links",
    "site:anita.* Women's Air Control Sports Bra",
    "site:delicatedaisys.* Radiant Rose Ultimate Skin Care Collection",
    "site:lovoda.* Coiled Hoop Earrings",
    "site:getcasely.* Off Tropic Floral | Exotic Orange Flower Case - Bold",
    "site:rta.* GUSTAVE COAT",
    "site:malarkeykids.* Teether Tether & Teether - Nautical & Baby Shark",
    "site:jiggypuzzles.* Dog Mom - Alja Horvat",
    "site:larssonjennings.* Classic Silver Bangle",
    "site:vibrantmiu.* HIGH RISE WIDE LEG in VINTAGE ACID WASH",
    "site:sohosocial.* Hey Shorty Fleece Short",
    "site:worldmoderndesign.* Eiffel Kids Chair",
    "site:mbare.* Auburn Iringa Basket",
    "site:daniel-patrick.* Loop Terry Standard Sweatshirt",
    "site:bogeyboys.* Essentials Hat - Bogey Brown",
    "site:yayaorganics.* Mineral Sunscreen Bundle - Sport SPF 50 & Baby+Kids SPF 50",
    "site:mercicollective.* Stayin' Alive Kit - All Eyes on Me Collar + Fly Away Toy",
    "site:thexbands.* The Full Body Gym Workout Kit",
    "site:sunnydazedecor.* Anjelica Polyresin Outdoor Flower Pot Planter",
    "site:legavenue.* Pop Star Costume",
    "site:movophoto.* HMT-2 | Desk Tripod With Mic Holder for WMX_HM",
    "site:instagram.* Deluxe Essentials Gift Box",
    "site:beyondbraid.* Blue Wave or Moss Camo 300 Yard Spools",
    "site:edikted.* Orchid Sheer Lace Top",
    "site:heritagesteel.* Eater X Heritage Steel 2 Quart Saucier With Lid",
    "site:edikted.* Lidia Sheer Mesh Bra Top",
    "site:letocollection.* Tattoo Mesh Racerback Bralette",
    "site:takeoutorder.* Bad News T-shirt",
    "site:caskata.* Hawthorne Gilt Bread & Butter Plate",
    "site:evafranco.* Cossette Dress",
    "site:karmagifts.* Holiday Oven Mitt & Spatula Set",
    "site:satechi.* USB a 3.0 to USB C Adapter Space Gray",
    "site:btiff.* PT115W B.Tiff Shooting Star Pendant Necklace",
    "site:jonathany.* Vienna 25.5 Ceramic LED Table Lamp",
    "site:hungovraf.* Cooling Hangover & Headache Cap - Tortoise",
    "site:lillarose.* Bow",
    "site:pontofootwear.* The Pacific Women's",
    "site:swingjuice.* Long Sleeve Men's Performance Hoodie Golf Strokes",
    "site:princesspolly.* Gibbs Mini Skirt",
    "site:ragnco.* Emmeth Studs Embellished Flat Sandals",
    "site:getcasely.* All You Need Is Love | Beatles Case  - Bold+MagSafe¬Æ",
    "site:pyleusa.* High-Quality Connection: 3 Ft HDMI Type A Male to HDMI Type D (Micro) Cable",
    "site:jambys.* Lavender/Mint",
    "site:k2snow.* Contour Snowboard Boots Women's 2024",
    "site:Flip.* Butterfly Vneck Crop Smocked Back Waist",
    "site:trueclassic.* Combo Boxer Briefs 6-Pack",
    "site:astoria-activewear.* Astoria LUXE BALANCE Miracle Sports Bra - Primrose",
    "site:mollyandstitch.* Butter Leather 3x Adjustable Dog Leash - Steel",
    "site:urbancharm.* Tourmaline Birthstone Stacker Ring by the Urban Charm",
    "site:beargrips.* Barbell Clamp Collars (Quick Release)",
    "site:midheavendenim.* Lani Light Mid-Rise Jean With Raw Hem",
    "site:estella-nyc.* Baby Rattle | Hot Dog",
    "site:westernrise.* Spectrum Jogger - Short 29",
    "site:athinacollection.* Casual Hoodie Dress",
    "site:hugglehounds.* Scout Perfect Bolster Bed",
    "site:agolde.* Lana Mid Rise Straight in Sway",
    "site:beargrips.* Organic Ashwagandha| Stress & Anxiety | 60 Cap",
    "site:ds.* Bohemian Crochet Patchwork Sleeveless Tunic",
    "site:threadedpear.* Saylor Crossbody",
    "site:nodny.* Crochet Pocket  Top",
    "site:bermies.* Blue to Waves - Boy¬¥s Swim Trunks",
    "site:easy-clothes.* Ecru Conrad Sweater",
    "site:alayanaturals.* Multi Collagen",
    "site:superiorfarmspet.* Case of 10 Cheek Roll Peanut Butter Flavored 5 - 6",
    "site:gilliclothing.* Hello Beautiful Short Sleeve Sweater Top",
    "site:athinacollection.* Peplum Panache Denim Jacket",
    "site:ragnco.* Pin-Up Braided High Heel Sandals",
    "site:inimigo.* Boiler Basic Hoodie",
    "site:pumagolf.* Men's Gs-Fast Golf Shoes",
    "site:fashiongo.* High Waist PU Leather Corset Cincher  Pants",
    "site:everydaycalifornia.* Cambria Tee",
    "site:monkvee.* MonkVee¬Æ Original Monk Fruit Sweetener - 2X Supply",
    "site:readerest.* Magnetic Eyeglass Holder",
    "site:arborcollective.* Foundation Rocker Snowboard 2024",
    "site:cozyearth.* Women's Stretch-Knit Bamboo Lounge Tee",
    "site:artoftea.* Ultimate Iced Tea Kit",
    "site:sisterbees.* Cozy Bee Beeswax Candle - Farmhouse Style Glass Jar",
    "site:threesixty6.* Original TSS Dry-Fit Golf Polo for Men",
    "site:legavenue.* Book Smart Babe Costume",
    "site:modernbeast.* DAD TATTOO TEE",
    "site:suavshoes.* Women's the Zilker",
    "site:threesixty6.* Golf Hoodie Pullover",
    "site:bermies.* Party Pants - 4 inseam swim trunks",
    "site:fameaccessories.* Wide Brim Straw Weave Hat",
    "site:homecourt.* Hand Cream",
    "site:edikted.* Lace Bow Asymmetric Top",
    "site:westcoastjewelry.* Polished Stainless Steel Skull and Black Lava Strech Bracelet",
    "site:gainsinbulk.* Real Vitamin C",
    "site:vinevida.* Palo Santo Essential Oil",
    "site:pmdbeauty.* Shower Spa Kit",
    "site:ragcompany.* Minkles Patent Pu Statement Block Heel Long Boots",
    "site:anastasiabeverlyhills.* Brow Beginners Kit",
    "site:salomon.* QST Access 80 Ski Boots 2024",
    "site:princesspolly.* The Love Galore Romper",
    "site:babyktan.* Country Girl Onesie",
    "site:geminisound.* AS-12BLU-LT-PK: 12 Multi-LED Bluetooth Speaker Package",
    "site:princesspolly.* Terah Set White",
    "site:karmagifts.* Tank Top",
    "site:dogheliosbrand.* 'Arctic Blast' Full Bodied Winter Dog Coat W/ Blackshark Tech",
    "site:Flip.* Yoga Band Buttery Soft Print Leggings",
    "site:winxandblinx.* Sorbet Raspberry Hooded Towel",
    "site:magnlens.* Essential Watts Oversized Hoodie",
    "site:foreverylivingthing.* Kids Carrots Butterfly Tee",
    "site:vibrantmiu.* High-Rise Color Block Wide Jeans",
    "site:karmagifts.* Thin Headbands",
    "site:instantfigure.* Insta Slim I.S.Pro USA Power Mesh Compression Sleeveless Crew Neck ",
    "site:instagram.* FLOWER PUFF TEE",
    "site:leliscollection.* USA KNIT TNK TOP",
    "site:mossamigos.* Moss Rico",
    "site:nolecare.* Shampoo & Conditioner Set (Starter Kit)",
    "site:ruggable.* Jonathan Adler Inkdrop Black & Ivory Tufted Area Rug - Washable Rug Cover",
    "site:nutrichefkitchen.* Effortless Cooking: Nonstick Kitchen Cookware Set",
    "site:fashiongo.* Cowboy Take Me Away Graphic Top",
    "site:scientificanglers.* Frequency Trout Double Taper Fly Line",
    "site:hyfve.* Soul Mate Drop-Shoulder Cropped Sweatshirt",
    "site:notsoape.* Longline Jacket",
    "site:virvita.* Violette Linen Vest",
    "site:jackieaslick.* Zip Up Long Sleeve Active Outerwear",
    "site:donatellogian.* Lab Created Round LeverBack Earrings",
    "site:getcasely.* Here Comes the Sun Colorblock Sunset Case - Classic",
    "site:setactive.* SCULPTFLEX¬Æ BIKE SHORTS - GALAXY",
    "site:luxclub.* 7 PC Split King Sheet Set",
    "site:shopwearwell.* The Sofia - Narrow",
    "site:princesspolly.* Elvia Mini Dress",
    "site:shbamovement.* 07 Apex Military Shorts (Liner, Black)",
    "site:gersoncompany.* Deluxe 4 Piece Jefferson Pine Holiday Decor Set With Clear and Warm White Lights",
    "site:sodapup.* Snowman Durable Rubber Chew Toy & Treat Dispenser",
    "site:bigbrandproducts.* 17Pcs Electric Foot Callus Remover with Vacuum",
    "site:dameliofootwear.* Kamila Pump - Gold",
    "site:sundayswagger.* Reboot",
    "site:estella-nyc.* Organic Baby Gift Set | Food Onesie & Rattle",
    "site:instantfigure.* Fabulous Push-Up Bra 158032",
    "site:zwilling.* ZWILLING Pro Knife Block Set",
    "site:laticoleathers.* Grit Crossbody",
    "site:patchaid.* Rise And Shine Vitamin Patch Pack",
    "site:gefu.* Meat Mincer 7/8 14710",
    "site:jellycomb.* B094 Travel Cable Organizer Cord Storage Bag",
    "site:goodforsunday.* Tencel Notch Collar Shirt",
    "site:touchdogbrand.* Onesie Lightweight and Breathable Full Body Dog Pajamas Jumpsuit",
    "site:australianglow.* Fierce And Flawless Kit",
    "site:toastedjewelry.* Hammered to Perfection Bangle",
    "site:athinacollection.* It Feels Like Fall Midi Dress",
    "site:sendaathletics.* Ushuaia Academy Futsal Shoe - Women",
    "site:btiff.* RG074MW B.Tiff Tension 1 Ct Moissanite Round Solitaire Engagement Ring",
    "site:emoryparkclothing.* CAP SLEEVE BODYCON DRESS WITH OPEN BACK",
    "site:objectshq.* Harriet 62 In. Floor Lamp",
    "site:globalcutleryusa.* Classic 2 Piece Forging Knife Set",
    "site:aroma360.* Belle Collection Set",
    "site:organicbasics.* True Regular Fit Tee",
    "site:easy-clothes.* Black and Taupe Floral Drew Dress",
    "site:princesspolly.* Field of Dreams Maxi Dress",
    "site:kswiss.* Men's Hypercourt Express 2 Tennis Shoes - Medium Width",
    "site:halftee.* The Classic 3/4 Sleeve Halftee",
    "site:kooniez.* Hoodie - Navy Tie-Dye Patchwork",
    "site:goldilocksgoods.* Swedish Dishcloth: Rainbow",
    "site:thehandloom.* Echo Mini Shirt - Baby Blue",
    "site:princesspolly.* Everlasting Satin Platform Heels",
    "site:hausandhues.* Black sun (Unframed)",
    "site:donatellogian.* Sterling Silver 925 Double Curb Chain 2MM - Double Link Chain Necklace",
    "site:clecosmetics.* RENEWAL RITUAL SET VOL.‚Ö°",
    "site:alalastyle.* Qalo Metallic Classic Silicone Ring",
    "site:shopatkon.* Women's Multi Stripe Button Front Midi Skirt in Rust Multi",
    "site:ellabonna.* Muslin Stay on Baby Booties Lilac",
    "site:carawayhome.* Double Burner Griddle",
    "site:stepone.* Boxer Brief - Wacky Dackys",
    "site:686* Men's SMARTY 3-in-1 Form Jacket",
    "site:petersonhousewares.* Calling Stag Metal Wall Art",
    "site:shopatkon.* Women's V-Neck Basic Blouse",
    "site:setactive.* NYLON HALF ZIP WINDBREAKER - HIDEAWAY",
    "site:simmsfishing.* Men's Tributary Stockingfoot - Short Inseam",
    "site:fameoncentral.* BASIC HIGH V TEE LS-PEACH",
    "site:blomus.* LAMURA Marble Wall Hooks",
    "site:ragcompany.* GOOSE-FEATHER Antique High Heeled Ankle Boot",
    "site:princesspolly.* Keyton Bikini Top",
    "site:kalencombaby.* Sweet & Fun Sensory Plush Ball",
    "site:elunausa.* Plus Animal Mix Volume SL Top",
    "site:findmenowthelabel.* Plush Bandeau Bralette",
    "site:adinaeden.* Pave X Solid Twisted Open Drop Stud Earring",
    "site:ninexisusa.* Full Size Waffle-Knit Ruffle Hem Hoodie",
    "site:avenuezoe.* Button Up Shirt Set",
    "site:naturanectar.* Drug Free Menopausal Symptom Relief* with EaseFemin by Naturanectar",
    "site:agolde.* Cooper Trouser in Command",
    "site:one33social.* The Madison | Blue Paillette Mini Dress",
    "site:catricecosmetics.* Glam & Doll Easy Wash Off Power Hold Eyeliner",
    "site:loveprayjewelry.* Communication and Calm Aquamarine Moonstone and Quartz Delicate Necklace",
    "site:msskincare.* Enlighten| Retexturizing Glycolic Treatment",
    "site:laurengadams.* Layers of Love Stackable Ring - Round",
    "site:threesixty6.* Fleece Half Zip Mock Button Golf Sweater",
    "site:vibetumblers.* VIBE 28oz Insulated Tumbler ",
    "site:buddhapants.* Solid O.G. Harem Pants",
    "site:threesixty6.* Golf Hoodie Pullover",
    "site:marketstudios.* GRATEFUL DEAD X SHAKA 3 PACK",
    "site:trueclassic.* Carbon Tall Active Crew Neck",
    "site:billyreid.* LEROY SHIRT JACKET",
    "site:h2ocapsule.* Neutral - Cube - Half Gallon Water Bottle with Storage Sleeve and 2 lids",
    "site:serenelifehome.* Waterproof Boat Bimini Top Cover",
    "site:otterbox.* Otterbox Premium Fast Charge USB C Cable 2m",
    "site:urbancharm.* Sapphire Birthstone Stacker Ring by the Urban Charm",
    "site:loveokko.* Signature Thong",
    "site:costanova.* Pacifica Ramen Bowl Set",
    "site:farbank.* Rio Scandi Short Fly Line",
    "site:trxtraining.* YBELL¬≠ Pro Series",
    "site:adinaeden.* Scattered Beads Hoop Earring",
    "site:nodny.* Corduroy Puffed Sleeve Jacket",
    "site:blueoceanpearls.* .925 Sterling Silver Freshwater Pearl Bracelet - 8 in",
    "site:popupsbrand.* EVERYDAY TOTE",
    "site:unlesscollective.* Mammut x UNLESS Mountain Day Tee",
    "site:santegrace.* The Flightsuit - Cupro Jumpsuit",
    "site:pyleusa.* 2 Parking Sensor System & Led Display",
    "site:thehundreds.* Moth Snapback",
    "site:eklexic.* XL ALTERNATING TWISTED LINK TOGGLE NECKLACE",
    "site:foreverylivingthing.* Texas Chainsaw Massacre Photo Tee",
    "site:shopatkon.* Konus Men's Scuba Bomber Jacket ",
    "site:getcasely.* Come Together | The Beatles Abbey Road Case - Classic+MagSafe¬Æ",
    "site:jonathany.* Peralta Moroccan Diamond Indoor/Outdoor Area Rug - Rectangle",
    "site:cloverbyclove.* Super Slick Lip Jelly",
    "site:ailiscorner.* Harper Silicone Beaded Key Ring Bracelet",
    "site:speckproducts.* Presidio Perfect-Clear with Impact Geometry MagSafe iPhone 14 Pro Max Cases",
    "site:daniel-patrick.* Surplus Logo Hoodie",
    "site:deluc-official.* Blanchard Vegan Leather Shorts",
    "site:porijewelry.* 10K Gold Long Anchor Chain Necklace",
    "site:ds.* Lace Crochet Splicing v Neck Loose Fit Tank Top",
    "site:elianamaternity.* Eliana Shoulder Tie-Knot Maternity Overalls - Stretchy Maternity Romper Shorts",
    "site:bytesscollection.* Kim Skirt",
    "site:redmooseusa.* Brushes",
    "site:ancientindia.* Intense Hydration Squalane Face Cr√®me",
    "site:firedeptcoffee.* RUM INFUSED, WHOLESALE COFFEE - Whole Bean",
    "site:flip.* Tie Neck Butterfly Sleeve Blouse",
    "site:princesspolly.* Just Like That Maxi Skirt Grey",
    "site:tecnifibre.* TF-X1 285 Racquet Unstrung",
    "site:weruva.* Dogs in the Kitchen the DOUBLE DIP Wet Dog Food ",
    "site:vienatura.* Happy HalloThanksMas Unisex classic tee",
    "site:antisocialsocialclub.* ASSC Ghost Berlin Tee S/S- GREY HTR",
    "site:mnml.* Anime L/S Jersey - Multi",
    "site:wonderandwise.* Cash Register",
    "site:vintagehomeusa.* 70 Heavenly Bamboo Tree With Vibrant Fall Colored Leaves | Beautiful Indoor Fall Decor",
    "site:pontofootwear.* Ministry of Supply X Ponto PlantForm Pacific - Sepia (Men's)",
    "site:edikted.* Serafina Sheer Mesh Tank Top",
    "site:livdapparel.* Laufey Pleated Bodice Maxi Dress",
    "site:hippiecrafter.* Watercolor Brush Pens",
    "site:thecaep.* Universal Phone Hitch + Gold Paperclip Crossbody",
    "site:angrysale.* Multipurpose Pet & Animal Gloves - for De-shedding, Bathing, Grooming",
    "site:instagram.* Colt Mens Heated Vest With Hood ",
    "site:jeans.* Men's Southwestern Cardigan",
    "site:zwilling.* BBQ+ 10-Pc Grill Essential Set",
    "site:modaxpressonline.* Distressed Stretchy Skinny Jeans",
    "site:shopwearwell.* The Carmen - Standard",
    "site:jackieaslick.* Smile Face Adjustable Baseball Caps",
    "site:princesspolly.* Nolan Mini Dress",
    "site:youngdays.* Madison Shorts",
    "site:bewicked.* Kimmie Robe",
    "site:vintagehomeusa.* 68 Magnolia Tree",
    "site:smithoptics.* Squad Goggles",
    "site:oliviaandjackson.* Brass Gold 3-Piece Curb/Paperclip/Rope Chains Layered Necklace",
    "site:featclothing.* Jana Kramer x feat BikeShort",
    "site:bayeas.* HIGH RISE FLARE JEANS WITH SLIT",
    "site:urban-classics.* Eagle Tee",
    "site:pixiemood.* Initial Letter Charm made with Recycle Bottles",
    "site:balielf.* Samara Convertible Midi Dress",
    "site:arfpets.* Pet Steps with Built-In House",
    "site:thehandloom.* Mia Side Ties Top - Natural With Gold Stripes",
    "site:princesspolly.* Ayra Lace Mini Skirt",
    "site:bayeas.* Skinny Cropped Jeans",
    "site:jonathany.* Amir Moroccan Beni Souk Area Rug",
    "site:walden.* Meditation Cushion + Mat Set",
    "site:getcasely.* Classic Black iPhone Ring & Kickstand",
    "site:ccilu.* Greenplax Fish",
    "site:rader.* Friends of the Family Porcelain Vase",
    "site:butterandme.* Butter Spread Lip Balm",
    "site:babybibi.* Baby ABC & Numbers Bath Books",
    "site:dcshoes.* Lotus Snowboard Boots Women's 2024",
    "site:uninterrupted.* More Than An Athlete Attribute Tee Blue",
    "site:instagram.* Quilted Puffer Jacket With Pockets",
    "site:ghostgolf.* MAX",
    "site:scientificanglers.* Absolute Trout Leader 7.5 ft Single Pack",
    "site:shopatkon.* Women's Sleeveless Lace Up Top",
    "site:instagram.* EASY HOUR GRAPHIC TERRY SHORT",
    "site:milkmakeup.* Pore Eclipse Matte Translucent Setting Powder",
    "site:conair.* BaBylissPRO VIBEFX 2-Speed Cord/Cordless Massager, Gold",
    "site:karmagifts.* Holiday Flour Sack Tea Towels With Charm",
    "site:urbancharm.* Baby Blue Leather Color Band Bracelet",
    "site:shopatlasgrey.* Organic Oversized Knit Sweater",
    "site:billyreid.* CHINO SHORT",
    "site:gersoncompany.* 7.5 Ft. Pre Lit Clear LED Sparse Rainier Pine",
    "site:ccs.* CCS Hammer Loop Jean Shorts",
    "site:bermies.* Seagulls - Boy¬¥s Swim Trunks",
    "site:jvtextile.* 100 Dollar Bill Area Rug Mat",
    "site:loveyourmelon.* White Speckled Knit Crewneck Sweater",
    "site:thenorthface.* Women's Summit FUTUREFLEECE LT Zip",
    "site:antisocialsocialclub.* ASSC DISSOCIATIVE HOOD SS- BLACK/PURPLE",
    "site:smartyhadaparty.* Pink Flat Round Disposable Plastic Dinner Plates",
    "site:sunnydazedecor.* All-Weather Lake-Style Adirondack Chair With Cup Holder",
    "site:princesspolly.* Charvi Long Sleeve Mini Dress ",
    "site:fashiongo.* Fashion Sling Bag Backpack",
    "site:aviathletics.* Cross-Court Pickleball Skirt Inverted Pickleball Pocket Black Beauty",
    "site:storyspark.* DJ Turtle T-Shirt",
    "site:vervetdenim.* High Rise Slim Bootcut Jeans",
    "site:subtleartstudios.* GLASS TILE COASTER - Through a Window - Gray Gradient",
    "site:eptmusa.* Vintage Carpenter Pants",
    "site:virvita.* Aurelia Top Sustainable Modal",
    "site:joolbaby.* Sliding Cabinet Locks",
    "site:altfragrances.* Saxophone",
    "site:subtleartstudios.* Incense Holder - It's Lemon",
    "site:livdapparel.* Mona Midi Dress",
    "site:princesspolly.* Tranquilis Shirt",
    "site:evercado.* Satin Button Down Midi Dress",
    "site:sunnydazedecor.* 40 Four Star Large Fire Pit Table With Spark Screen",
    "site:gharyan.* Olive Wood Bread Slicing Board",
    "site:flybirdfitness.* Flybird All-in-One Power Rack With Pulley System Set",
    "site:shopwearwell.* The Elena - Narrow",
    "site:trueclassic.* Blues V-Neck T-Shirt 3-Pack",
    "site:popsmith.* Classic Kettle Popcorn",
    "site:instagram.* POUR SOME GRAVY ON ME SWEATSHIRT",
    "site:goat.* Gap Engineered by Balenciaga Logo 3/4 Sleeve Tee",
    "site:basicbae.* Full Size Ribbed Round Neck Slit Knit Top",
    "site:gentlemenrepublic.* Oceano Gel",
    "site:claudiagcollection.* Leni Necklace",
    "site:walterbaker.* Laureen Pant, Red Wood",
    "site:annvafashion.* Long Dress With Hoodie",
    "site:jackieaslick.* Simple Turtleneck Sweater",
    "site:prosourcefit.* XFit Power Resistance Bands",
    "site:vervetdenim.* Super High Rise Distressed Crop Straight Jeans",
    "site:playboy.* Checkered Flag Hoodie",
    "site:trulycontagio.* Popular Beanie",
    "site:mnml.* B505 Contrast Flare Denim - Blue",
    "site:glossmoderne.* Clean Luxury Roll-on Perfume Oil - R√™ves",
    "site:ragcompany.* GREAT-STORM Suede Leather Calf Boots",
    "site:instagram.* Ibex Mens Heated Workwear Vest ",
    "site:one33social.* The Gabby | Black Mini Cocktail Dress",
    "site:cookmagnifique.* Oval Slow Cooker - Manual",
    "site:grownasfoods.* Mac & Cheese + Hot Sauce Bundle",
    "site:heiressbeverlyhills.* Black Crepe Plunge Neckline Fur Mini Dress",
    "site:repriseactivewear.* Sage Legging",
    "site:akings.* VELOUR TRACK JACKET",
    "site:marketstudios.* ARCMES T-SHIRT",
    "site:guess.* Teddy Bear Necklace",
    "site:youngdays.* Ithaca Onesie",
    "site:classictouchdecor.* Smoked Glass Bowl with Scattered Gold Design",
    "site:mylesapparel.* Everyday Pant in Dusty Olive 32",
    "site:princesspolly.* Hills Halter",
    "site:eastxeast.* Freya Maui Sands Bikini Top",
    "site:vervetdenim.* Mid Rise Raw Hem Crop Skinny",
    "site:suzylevian.* Gold over Silver Brown Cubic Zirconia Animal Print Ring",
    "site:princesspolly.* Aarti Set",
    "site:jackieaslick.* JES High-Top Canvas Shoes Men's",
    "site:beverlyrug.* Egg Yellow Non-Slip Washable Kitchen Rug",
    "site:limericki.* Indigo Stripe Rash Guard",
    "site:miamod.* Year Round Pleated",
    "site:angelapparel.* Lace Up Mock Neck Top",
    "site:thermarest.* Therm-a-Rest Trail Scout Sleeping Pad",
    "site:getcasely.* XOXO | Candy Hearts Case - Bold",
    "site:blissy.* Classic Robe",
    "site:farmersdefense.* Protection Sleeves - Antique Bloom",
    "site:mommapots.* 5 Flower Vase - High Quality Porcelain",
    "site:benbenapparel.* Kids 3 Pack Pajamas Girls - Super Soft Cotton",
    "site:lonarc.* Meraki Dress",
    "site:roshambo.* Zack Morris Shades | Adult",
    "site:aaronprobyn.* CLIFTON Metal Hanging Plant Pot",
    "site:anna-kaci.* Renaissance Boho Lace Maxi Dress",
    "site:yogasleep.* Dohm¬Æ Sound Machine",
    "site:fragranza613.* Mish",
    "site:drinktru.* 7 Pack Sampler",
    "site:taylormadegolf.* Golf Qi10 MAX Fairway Wood - Right Handed - Stiff Shaft Flex",
    "site:quillfinejewelry.* Bree Dainty Snake Gold Chain Ring",
    "site:mokufoods.* Hawaiian Teriyaki Mushroom Jerky",
    "site:olababy.* Silicone Sleeve for Avent Natural Glass Bottle",
    "site:glassyeyewear.* Walker Plus",
    "site:evercado.* Halter Neck Tulle Mini Dress",
    "site:rossignol.* Evader Snowboard 2024",
    "site:sandcloud.* Pearl Bundle",
    "site:buddhapants.* Reggae Vibes Only T-Shirt",
    "site:hyfve.* BY YOUR SIDE POLKA-DOT TOP and MIDI SKIRT SET",
    "site:shopatkon.* Women's Lurex Yoryu Ruffle Dress in Black",
    "site:cangshancutlery.* Haku Series Carving Set 2 Piece Set",
    "site:jambys.* Breathable No-Sweat Sweatpants",
    "site:getbullish.* 70's Baby Retro Jersey Short Sleeve Tee",
    "site:ragnco.* Edmanda Tassle Detail Leather Mules",
    "site:jewelrybyhannahb.* The 18K Gold Filled Beaded Kids Emoji Charm Necklace - 16",
    "site:ds.* Half Button v Neck Patched Pocket Tank Top",
    "site:lostdaze.* Cavern Jeans",
    "site:youngandreckless.* Upper Decky Tee",
    "site:misen.* Misen Minis - Gray Serrated Knife",
    "site:keababies.* Jumbo Toddler Pillow with Pillowcase",
    "site:houseofparty.* Christmas Single Color Garland",
    "site:catricecosmetics.* Clean ID Pure Eyebrow Pencil",
    "site:hybridnationclothing.* HYBRID NATION KIDS S/S UNITY TEE",
    "site:maralabel.* Red Sunset Silk Halter",
    "site:santandabel.* Men's Red Stripe Jersey Sleep Shorts",
    "site:shopdirectdeals.* Zulay Kitchen 16Pc Porcelain Dinnerware Set",
    "site:fashiongo.* Beach Side Ready to Go Graphic T Shirts",
    "site:refinerynumberone.* Bohemian, Gorgeous Abstract Flowers, Boho Floral Design, Summer Vibes, Gardening, Festival, Nature Shirt",
    "site:twillory.* AIR Pants // Tailored Fit // Length 30",
    "site:noenddenim.* Quinn Wide Leg Trouser",
    "site:beflaxlinen.* Duvet Cover Set",
    "site:sassywoof.* Dog Bundle - Spill the Tea",
    "site:definitearticles.* Sustainable Riverline Racerback Sport Bra - Tested BPA + PFAS Free",
    "site:686* Men's SMARTY 3-in-1 Form Jacket",
    "site:princesspolly.* Battersea Top",
    "site:shopvustra.* Ash Rose Short Sleeve Henley",
    "site:kinflyte.* Rise Zip Bra - Eco Jersey",
    "site:weiv.* Active Sports Performance Running Short",
    "site:sttelli.* Suction Toothbrush Holder",
    "site:oliveandivorywholesale.* Bella Canvas Unisex Long Sleeve Tee",
    "site:tonymoly.* 24K Snail Everywhere Repair Gel",
    "site:playboy.* Color-Block Sweatpant",
    "site:mia-bijoux.* Soulmate Pendant Necklace ",
    "site:ewingathletics.* 33 HI OG ",
    "site:sassywoof.* Dog Sailor Bow - Picnic Fur Two",
    "site:sanlorenzohawaii.* Coral Oceanic Lilac Braided Thong Bikini Bottom",
    "site:areohome.* Gideon Lidded Basket",
    "site:babolat.* Babolat VS Original Overgrip",
    "site:brutusandbarnaby.* Sweet Potato Slices",
    "site:gianato.* PIETRO",
    "site:public-supply.* 3.5x5.5 - Pocket Notebook - Embossed",
    "site:saltypun.* Men's Basic Baby Blue",
    "site:uninterrupted.* Los Angeles Circle Logo Tee Blue",
    "site:yuda.* Hydration & Hormone Support Bundle",
    "site:sheswaisted.* Smoothing Seamless Open-Back Bodysuit",
    "site:gilliclothing.* STRIPE OVERSIZED SWEATER",
    "site:asics.* Asics Men's GEL-Resolution 9 Tennis Shoes - Medium Width",
    "site:marketstudios.* SHERWOOD GD DEADWOOD HOODIE",
    "site:loomini.* 1 Set Dual Tip Marker Pen Set | Choose From 24, 36, 48, 60, or 80 Colors",
    "site:agolde.* Low Slung Baggy (Corduroy) in Wig",
    "site:beverlyrug.* Washable Non-Slip Sports Area Rug Pink Girl",
    "site:ashandrose.* Summer Picnic Wristlet Purse",
    "site:mnml.* Every Day Hoodie",
    "site:angrysale.* Racerback Seamless Sports Bra for Gym FItness and Yoga",
    "site:doralarsen.* CYDNEY LACE TRIM BRALETTE",
    "site:princesspolly.* Juzen Maxi Dress",
    "site:goodforsunday.* Essential Bamboo Sweatshort",
    "site:youngdays.* Princeton Pants",
    "site:avenuezoe.* Heart Cow Print Seed Beaded Earrings",
    "site:osprey.* Talon 11 Backpack- Men's",
    "site:amatostyle.* AS X WLG SMALL DAGGER NECKLACE",
    "site:carawayhome.* Cookware Set",
    "site:barbasolelectric.* Rose Gold Cuticle Nipper",
    "site:dockatot.* OPEN BOX: Cabana Kit for Deluxe+ Dock - Rose",
    "site:featclothing.* Mens BlanketBlend Shorts",
    "site:luminesscosmetics.* Airbrush Bronzer",
    "site:aemiandco.* Mae Dress",
    "site:shoporangefarm.* Light Sweater Dress",
    "site:kinflyte.* Freedom Bra Midi - Eco Jersey",
    "site:axwellwallet.* Cover Plates - Army Green",
    "site:celestestyle.* Celeste Full Size Houndstooth & Leopard Roll-Tab Sleeve Top",
    "site:orvis.* Clearwater Fly Rod - 10'0",
    "site:hausofbrilliance.* .925 Sterling Silver 1.0 Cttw Diamond Miracle-Set X-Link 7 Tennis Bracelet (I-J Color, I3 Clarity)",
    "site:princesspolly.* Emily Maxi Skirt",
    "site:princesspolly.* Cherry on Top Maxi Skirt",
    "site:littleskystone.* Initial Bracelet - w",
    "site:repriseactivewear.* Wear Plants Crop Tee",
    "site:karmagifts.* Crew Socks",
    "site:organicbasics.* Core Full Coverage Bra",
    "site:ullabellebaby.* Bento Lunchbox",
    "site:trulycontagio.* CC Confetti Lined Head Wrap",
    "site:lola-jeans.* KATE-SAGE High Rise Slim Jeans",
    "site:enzacosta.* BIAS CUT CAMI",
    "site:trueclassic.* Indigo Polo",
    "site:trueclassic.* Military Green Fleece French Terry Short",
    "site:rta.* ALE SWEATER | BLACK",
    "site:shopwearwell.* The Moccasin - Very Wide",
    "site:bandier.* Center Stage Contrast Legging - Lollipop/Tango Red",
    "site:repriseactivewear.* Bloom Skirt",
    "site:threesixty6.* Men's Solid Collarless Golf Polo",
    "site:lyxpro.* LyxPro XLR Cable - Male to Female",
    "site:wusthof.* W√úSTHOF Classic Knife Block Set Acacia 15 Piece Set",
    "site:yonex.* Yonex EZone Ace Racquet Strung",
    "site:edyson.* Claude High Rise Short",
    "site:blizzard-tecnica.* Cochise 130 Ski Boots 2024",
    "site:stephenjosephgifts.* Sunglasses",
    "site:edyson.* Vincent High Rise Roll Up Wide Leg Jeans",
    "site:adidas.* Men's Adizero Ubersonic 4.1 Tennis Shoes",
    "site:cgklinens.* 4PC Sheet Set - Extra Soft & Cooling Bed Sheets - Deep Pockets, Easy-Fit, & Wrinkle Free Sheets",
    "site:1822denim.* MATERNITY BUTTER SKINNY JEAN",
    "site:aroma360.* Blue Moon.",
    "site:mustardseedla.* Halter Neck Romper Dress",
    "site:prenelove.* Greystone Messenger Bag",
    "site:andreeva-online.* Baby Blue Knit Skirt With Handmade Details",
    "site:zulaykitchen.* Flour Sifter",
    "site:numnumbaby.* Straw Training Cup",
    "site:tomorrowslaundry.* Modern Essential Tee",
    "site:speckproducts.* IMPACTHERO Grip OnePlus Nord N30 5G Cases",
    "site:petmate.* Basic Cat Litter Pan Mouse ",
    "site:loveprayjewelry.* Sandalwood Throat Chakra Mala Necklace",
    "site:edikted.* 08 Velour Shorts",
    "site:apothekeco.* Sea Salt Grapefruit Scent Tower Diffuser Fragrance Oil",
    "site:shopnocturne.* Feather Boa Mini Dress",
    "site:mollyandstitch.* Butter Leather Dog Collar - Brass",
    "site:somethingglitter.* 2ct Dew created white moissanite and 1/10ct tw diamond solitaire engagement ring in 14k gold",
    "site:instagram.* MMShoes Arms Around Me Open Toe Slide",
    "site:paikka.* Recovery Raincoat Camo for Dogs",
    "site:trueclassic.* 9.5 Sandstone Comfort Chino Shorts",
    "site:head.* Edge 110 HV GW Ski Boots 2024",
    "site:karmaandluck.* Higher Self - Azula Silk Satin Scarf",
    "site:lonarc.* Zamba Bottom - Additional Straps - Latin",
    "site:shopatkon.* Canvas Button Down Shirt With Detachable Patch Pockets in Black",
    "site:lovepixart.* DIY BRICK KIT Super Mario Bros",
    "site:fashiongo.* HAPPY LEOPARD LONG SLEEVE TEE",
    "site:winxandblinx.* Wild Rabbit silver Minky Baby Blanket",
    "site:youngdays.* Eco-Friendly, 100% Organic Cotton Tee (Biloxi Tee)",
    "site:shopatkon.* Women's Long Sleeve Turtle Neck Fitted Top",
    "site:colsenfirepits.* Colsen Round Tabletop Fire Pit",
    "site:blumehomeware.* Disco Ball Planter",
    "site:paperplane.* On the Radar X Paper Planes Tee",
    "site:capellaapparel.* Eyelash Lace Trim Cami Mini Dress",
    "site:dressupamerica.* Gold King's Crown - Kids",
    "site:happymoose.* Juice Discovery",
    "site:bartonwatchbands.* Samsung Galaxy Watch5 Sailcloth Quick Release Royal Blue Watch Band",
    "site:objectshq.* Andonno Power Loomed Rug",
    "site:venturepal.* 22oz/32oz Motivational Water Bottle With Silicone Straw - Comes With a Complimentary Cleaning Brush and Straw Brush",
    "site:pingora-gear.* Eco Friendly Chalk Bag",
    "site:shortylove.* Wonder - Large Crossbody Bag",
    "site:studiocult.* Squiggle Ring",
    "site:dreamfarm.* BBQ Clongs Tongs",
    "site:cozyearth.* Linen Sheet Set",
    "site:memorylane.* Outlaw Short",
    "site:ds.* Ribbed Drawstring Sides Cutout One Piece Swimsuit",
    "site:cozyearth.* Women's Ultra-Soft Bamboo Hoodie",
    "site:ffups.* Grocery Store Cheddar, 1.5oz",
    "site:kellyrosegold.* 10k Gold Xs Finger Bangle",
    "site:anastasiabeverlyhills.* Fuller Looking & Feathered Brow Kit",
    "site:vintagehomeusa.* 76 Vintage Real Touch Golden Edged Agave, Indoor/ Outdoor Plant",
    "site:raeliv.* Wrinkle Effect Tiered Shirring Velvet Shirt",
    "site:blomus.* TELA Crochet Storage Basket Set",
    "site:adinaeden.* Pav√© Zig Zag Ring",
    "site:btiff.* PT318W B.Tiff Pave Bar Pendant - 2 Pendant",
    "site:getcasely.* Heart Throb | Endless Hearts Case - Bold + MagSafe¬Æ",
    "site:bossmanbrand.* Ultimate Beard Kit",
    "site:mpowerd.* Luci Solar Site Lights",
    "site:musclemilk.* 25g Protein Shake - 14oz",
    "site:winnielou.* Bison Burger Jerky Treats",
    "site:hotelcollection.* Serpentine Reed Diffuser",
    "site:trulycontagio.* Two-Tone Super Soft Popular Beanie",
    "site:eureka.* Mignon Libra Espresso Grinder",
    "site:stonelain.* Stella Porcelain Pasta Bowl Set - Set of 6",
    "site:woodleylowe.* Bekah Crew Sets",
    "site:myampd.* AMPD TPU / Acrylic Glitter Insert Case for Celero 5G (Gen 3)",
    "site:edikted.* Bayside Slitted Micro Skort",
    "site:agolde.* Fran Low Slung Straight in Invention",
    "site:yomtovsettings.* Premium Round Plastic Tablecloth | 96 Count",
    "site:instagram.* Linen Button Down Romper",
    "site:leliscollection.* SLEEVELESS MIDI DRESS",
    "site:purerosy.* Period Boy Short Underwear Heavy Absorbency ",
    "site:nicoleleeonline.* Printed Handbag With Three Pouches",
    "site:angelapparel.* Track Pant",
    "site:saysh.* Saysh One",
    "site:aviathletics.* Pickeball Jogger Custom Fabrics & Recycled Materials - Sapphire Blue",
    "site:trulycontagio.* Popular Beanie",
    "site:sassywoof.* Dog Collar - STAR WARS the Child",
    "site:kellyrosegold.* 10k Gold Raindrop Finger Bangle (Rose Gold)",
    "site:ateliersaucier.* Limonada Scalloped Oilcloth Placemat | Reversible",
    "site:memorylane.* Backdown Puffer Jacket",
    "site:adinaeden.* Solid Square Huggie Earring 14K",
    "site:yelete.* High Waist Tech Pocket Workout Capri Leggings",
    "site:princesspolly.* Ma Belle Sandals Suede",
    "site:verveculture.* Moroccan Poufs",
    "site:altfragrances.* Executianna",
    "site:jackieaslick.* Chic Crystal Necklace",
    "site:edikted.* Lacey Knit Tank Top",
    "site:farbank.* Crosswater Collection Combo -¬†9'0",
    "site:freshyworld.* Indies: Low Cut Sneaker Opulence! Soft Leather & Suede!",
    "site:popflexactive.* Crisscross Hourglass¬Æ Legging With Pockets (Soft Touch) - 25",
    "site:flybirdfitness.* Bundle: Adjustable Weight Bench FB299 W/ Hex Dumbbells",
    "site:kancanusa.* High Rise Distressed Slim Straight Jeans",
    "site:hyfve.* D-Linen Blended Top and Pants Set",
    "site:celestestyle.* Full Size Contrast Eyelet Ruffle Sleeve Blouse",
    "site:residence.* Don't Look",
    "site:buddhapants.* Kids Flower Harem Pants",
    "site:yogademocracy.* Movement Short in Electric Flow",
    "site:qalo.* Dakota Ring",
    "site:ripndipclothing.* Blunt Face Tee (Black)",
    "site:sterlingforever.* Evelyn Ring",
    "site:agolde.* Paulette Bodysuit in Shark",
    "site:jennywulace.* Papilio Ring ‚îÄ Light",
    "site:woodleylowe.* Ceci Sweater Sets",
    "site:subtleartstudios.* GLASS TILE COASTER",
    "site:shopwearwell.* The Moccasin - Slight Wide",
    "site:repriseactivewear.* Bloom Bra",
    "site:sttelli.* Radiance Towels - Wash Towel",
    "site:bareminerals.* GEN NUDE¬Æ Powder Blush",
    "site:daniel-patrick.* Standard V-Neck Tee",
    "site:angrysale.* Women Active Stretch Running Sports Tennis Skirt",
    "site:beverlyrug.* Waikiki Blue Trellis Outdoor Area Rug",
    "site:sanlorenzohawaii.* Essential Solids Dreamy Sky Classic Triangle Bikini Top",
    "site:ridesnowboards.* Lasso Snowboard Boots 2024",
    "site:callowaymills.* Paddle  Doormat",
    "site:btiff.* RG111W B.Tiff Stacking .01 Ct Eternity Ring [Thin Band]",
    "site:edikted.* Loullie Split Front Ruffled Top",
    "site:altesc.* [Wear] Drawcord ",
    "site:rebecca-allen.* The New Pump, Nude II",
    "site:vibrantmiu.* High Rise Distressed Skinny",
    "site:fashiongo.* Denim Jeans",
    "site:heimishusa.* Full Size Statement Neck Open Front Blazer",
    "site:otterbox.* Otterbox Commuter Lite Case for Samsung Galaxy A03s",
    "site:manifest-beauty.* DUBAI IT GIRL LIP KIT",
    "site:modernbeast.* MODERN CLASSIC COAT ",
    "site:gathre.* Mini",
    "site:casadilumo.* 'Do Epic Shit' LED Neon Sign",
    "site:sani.* Pearl Set (5'11-6'1 Height with Heels for skirt length)",
    "site:marmot.* Men's Variant Hybrid Hoodie",
    "site:sorme.* Refinee Line Stop Serum",
    "site:avenuezoe.* Cropped Fitness Top",
    "site:shopmsinger.* CLASSIC DECK POLO",
    "site:whollypup.* 12 Inch Super Beef Chew Stick",
    "site:shwallyhome.* Tallow & Magnesium Oil Cream",
    "site:gianato.* LORENZO",
    "site:portolano.* Ladies Tie Dye Slippers",
    "site:marketstudios.* BUTTERFREE HOODIE",
    "site:mollyandstitch.* Maritime Dog Leash - Steel",
    "site:pumagolf.* Men's Proadapt Alphacat Golf Shoes",
    "site:facileskin.* Core Four + Serum",
    "site:thirtytwo.* Lashed Snowboard Boots Women's 2024",
    "site:momeni.* Villa 05",
    "site:wallicases.* Blushing Leopard",
    "site:serenelifehome.* Safety on the Move: Coiled Ankle Cuff Safety Leash",
    "site:princesspolly.* Cecile Strapless Top",
    "site:obermeyer.* Boys' Gent's Jacket",
    "site:marketstudios.* MARKET LAKERS SWEATSHORTS",
    "site:milkmakeup.* Sunshine Under Eye Tint + Brighten",
    "site:adidas.* Men's Gamecourt 2.0 Tennis Shoes",
    "site:kancanusa.* Full Size High Rise Frayed Hem Denim Shorts",
    "site:avenuezoe.* Backless Yoga Jumpsuit",
    "site:nativaliving.* Woven Block Pillow Case - Natural With Black",
    "site:threesixty6.* Original TSS Dry-Fit Golf Polo for Men",
    "site:billyreid.* DIAMOND QUILT HALF ZIP",
    "site:princesspolly.* Lefler Top",
    "site:autumnalley.* 4 Piece Glass and Galvanized Bathroom Set",
    "site:sunnydazedecor.* Repeating Squares Cylinder Iron Outdoor Water Fountain",
    "site:recesspickleball.* Pink Hybrid Pickleballs ‚Äî Set of 3",
    "site:fashiongo.* Blessed Floral Graphic T Shirts",
    "site:threesixty6.* Men's Thin-Striped Collarless Golf Polos",
    "site:epdesignlab.* Illuminated Color Changing LED RGBW Inflatable Sofa",
    "site:bodrumlinens.* Pronto",
    "site:tossware.* RESERVE 8oz Stackable Rocks Tritan Copolyester Glass",
    "site:supreme.* Crew 96 Tee 'Navy'",
    "site:akings.* VELOUR TRACK JACKET",
    "site:theloomia.* Linen Bed Runner and Two Pillow Covers",
    "site:miamod.* MM SWAY SKIRT - AQUA 20",
    "site:amyandannette.* Round Sterling Silver Halo Omega Lever-Back Earring",
    "site:cubittofficial.* Classic Band | Cubitt Jr. and Cubitt Teens",
    "site:vitaparfum.* Olio Di Cara",
    "site:princesspolly.* Euphemia Maxi Dress ",
    "site:doralarsen.* ORLA LACE BALCONETTE BRA",
    "site:trueclassic.* Carbon Active Quick Dry Short With Liner",
    "site:hugglehounds.* NCAA Florida State University, Cimarron Knottie¬Æ Plush Dog Toy",
    "site:eklexic.* Zodiac Pendant Capricorn",
    "site:nylabone.* Healthy Edibles All-Natural Long Lasting Bacon Flavor Chew Treats - Wolf - Up to 35 Lb",
    "site:wpstandard.* Mr. Grumpy Leather Slippers (Men's)",
    "site:setactive.* Sculptflex¬Æ Bike Shorts",
    "site:adidas.* Men's Supernova Tennis Shoes",
    "site:fashiongo.* 2Pc Set Pant Suits",
    "site:elyontableware.* Ambrey 20 Piece Reflective Hand Forged Flatware Set High Quality Stainless Steel Silverware",
    "site:rags.* Essentials Tank With Chest Pocket Dress",
    "site:threadedpear.* Bag Straps | 30 Styles",
    "site:gethommey.* Junior Linen - Milkshake Cushion",
    "site:sanlorenzohawaii.* Coral Lemon Luster Thin Brief Bikini Bottom",
    "site:billyreid.* COCOON COAT SOLID",
    "site:cloudwaterbrands.* Logo Baseball Cap",
    "site:getbrewsy.* The Brewsy Starter Kit",
    "site:mylesapparel.* Seacliff Board Short in Deep Indigo",
    "site:psundays.* Pickle USA Tee",
    "site:edikted.* Lacey Ruffle Trim Fold Over Shorts",
    "site:santandabel.* Kids Christmas Candy Cane Short PJ Set",
    "site:stuhrling.* Rasa 3997A Quartz 40mm Classic",
    "site:vinadawines.* VINADA¬Æ - CRISPY CHARDONNAY (0%) 750 ML",
    "site:eptmusa.* 3M Triple Cargo Pants",
    "site:yogademocracy.* Rustica Printed Yoga Leggings - Extra Long (32)",
    "site:trueclassic.* Navy Hooded Long Sleeve T-Shirt",
    "site:getcasely.* Lonely Hearts Club | The Beatles Sgt. Pepper's Case - Bold",
    "site:rmjewelrync.* 2.00CTTW Stunning Heart Stud Earrings",
    "site:santandabel.* Women's Andy Cohen Yellow Terry Tennis Vest",
    "site:serenelifehome.* Propane Gas Fire Pit Stove Knob",
    "site:symphonybeauty.* Serums and Moisturizer Bundle for Dark Spots and Uneven Tone - 30mlx2 & 50ml",
    "site:trulycontagio.* CC Belt Bag Fanny Pack",
    "site:1people.* Seville SVQ - Short Sleeves Shirt - Licorice",
    "site:avenuezoe.* Glass Beads Chain Linked Earrings",
    "site:youngdays.* Eco-Friendly, 100% Organic Cotton Tee (Biloxi Tee)",
    "site:getcasely.* Sugar Plum Fairy | Winter Wonderland Case - Essential",
    "site:nuxactive.* Harper 7/8 Legging",
    "site:doodlecouture.* Pet Collar With Charm - Dune",
    "site:miamod.* MM SPRING KNIT COLOR BLOCK CARDI",
    "site:uvebeauty.* PURE Halo Antimicrobial Makeup Sponge",
    "site:somethingglitter.* 14K Yellow Gold pink and white Flower enamel stud Earrings",
    "site:lippyclip.* LippyClipKISS for Lip Drip | Gold Hardware",
    "site:princesspolly.* Jazzar Pocket Detail Pleated Pant Petite",
    "site:agolde.* Riley High Rise Straight Crop",
    "site:amerikanbasics.* Baseball Season Graphic Tee",
    "site:dameliofootwear.* Rayva Heel - Plaid",
    "site:farbank.* Rio Elite Switch Chucker Fly Line",
    "site:princesspolly.* Landon Mini Dress",
    "site:livdapparel.* Cami Neck Wide Legged Pocket Jumpsuit",
    "site:princesspolly.* Beresford Bodysuit",
    "site:thehundreds.* Palpatine Pullover",
    "site:kooniez.* Set - Dark Navy Tie-Dye - S Hoodie",
    "site:trulycontagio.* French Terry Cropped Jacket/Jogger Loungewear",
    "site:italic.* Emelie Featherlight Silk-Cashmere Knit Tee",
    "site:poweredbyrosebud.* Boob Planter With Drip Tray",
    "site:balielf.* Cherie Puff Sleeve Midi",
    "site:mnml.* Heavy Every Day Hoodie",
    "site:playboy.* April 1991 Cover Baby Tee Black",
    "site:rta.* CLYDE SHORT | PRISM PAISLEY",
    "site:sheepskin.* Ladies Sheepskin Bootie",
    "site:princesspolly.* Abeila Midi Dress",
    "site:billyreid.* DIAMOND QUILT HALF ZIP",
    "site:fameoncentral.* DRAWSTRING VELOUR SKIRT 35-GREY",
    "site:princesspolly.* Alrita Denim Skort Washed Black",
    "site:donatellogian.* Sterling Silver Simulated Diamond Marquise Cut Stud Earrings",
    "site:trueclassic.* Navy and White Commuter Long Sleeve Button Up 2-Pack",
    "site:bluebuffalo.* Tastefuls Adult Chicken Rice Dry Cat Food - 15 Lbs",
    "site:instagram.* SS Back Strap Dress - Solid Color",
    "site:oddiclothing.* Off the Shoulder Ruffle Blouse",
    "site:lola-jeans.* LIANA-RMN High Rise Shorts",
    "site:threesixty6.* Mens Two-Toned Colorblock Golf Polo",
    "site:eklexic.* 3 Ultimate Hoops",
    "site:tinilux.* Mini Celeste Stud Earrings",
    "site:thehundreds.* Disruptus Flora T-Shirt",
    "site:sheswaisted.* BootyBoosting Mid-Waist Zip Shorts",
    "site:mnml.* Rave Double Cargo Pants - Dusty Brown",
    "site:cramilosunglasses.* Half Frame Retro Oversize Aviator Sunglasses",
    "site:vinevida.* Helichrysum Essential Oil",
    "site:sunnydazedecor.* Water Fountain Statue With Children Playing At Faucet",
    "site:pynrs.* '23 Wendover Crop Tee",
    "site:shoporangefarm.* Front Pocket Textured Sweater Knit",
    "site:claimdefame.* Heather Fleece",
    "site:figgyplay.* The Figgy Expansion Pack - Add Waterproof Liners",
    "site:stuhrling.* Lustrous Harmony",
    "site:princesspolly.* Imelda Top",
    "site:mydoggytales.* Step in v Harness",
    "site:malbongolf.* VACAY",
    "site:oasissociety.* OASIS SOCIETY Daleyza - Chain Ankle Heel",
    "site:caskata.* Sea Fan Small Plates",
    "site:farbank.* Rio Fips Euro Nymph Fly Line",
    "site:creamyoga.* Blake Contrast Binding Sports Bra ",
    "site:magnlens.* Fossil 6'' Shorts",
    "site:gbrunostore.* GBruno - Pet Christmas Clothes Santa Claus Reindeer Antlers Costume Winter Outfit",
    "site:phantomgogo.* COMMUTER R1 SEATED SCOOTER",
    "site:shopraga.* Adil L/S Short Dress",
    "site:fifthandninth.* Harlow Rectangle Cat Eye Sunglasses",
    "site:michupet.* Michu Natural Clumping Tofu Cat Litter 5.5lb/88oz",
    "site:shopkook.* Stackable Soup Bowls, 23.6 oz, Set of 4",
    "site:babolat.* Men's Propulse Fury 3 All Court Tennis Shoes",
    "site:jambys.* Breathable No-Sweat Sweatpants",
    "site:ellabonna.* Organic Baby Booties, Newborn Booties Basic",
    "site:fameoncentral.* Covered Band Pleated Skirt 37-Black Wave",
    "site:princesspolly.* Ariah Long Sleeve Top",
    "site:edikted.* Pinstripe Low Rise Jeans",
    "site:retromarine.* Baywatch Red Swim Short",
    "site:avenuezoe.* High Cut Beach Cover-Up Dress",
    "site:anastasiabeverlyhills.* Limited-Edition Magnetic Case",
    "site:2undr.* Swing Shift Boxer Brief",
    "site:princesspolly.* Blaylock Triangle Bikini Top",
    "site:marinawestswim.* Salty Air Puff Sleeve One-Piece in Black",
    "site:card-addiction.* FULTON'S CLIP JOINT BOOTLEG EDITION PLAYING CARDS",
    "site:mushie.* Silicone Place Mat",
    "site:edikted.* Kadence Lace Trim Tank Top",
    "site:jackarcher.* Jetsetter Pants - 30 Long",
    "site:moonbath.* GOOD CLEAN FUN Pack of 6",
    "site:avenuezoe.* Stone Heart and Butterfly Earrings",
    "site:rudecosmetics.* Rainbow Spiked Base Pigment",
    "site:trulycontagio.* Ultra Soft Capri Leggings",
    "site:beachjoybikini.* Solid One Piece Swimsuit With Ruffle Detail",
    "site:weiv.* CHAIN LINK PRINT SHORT SLEEVE TSHIRT",
    "site:ezenana.* Brushed Melange Hacci Soft Oversized Sweater",
    "site:setactive.* CLASSIC COTTON MID TEE",
    "site:pomoca.* Climb 2.0 Ready2C 120mm CF V2 Climbing Skins",
    "site:princesspolly.* Marjorie Linen Set",
    "site:eptmusa.* Tekno Flare Pants",
    "site:karmagifts.* Table Top Birds Felt Ornament Set",
    "site:karmagifts.* Reese Pot Holder & Tea Towel Set",
    "site:avenuezoe.* CZ Numbers Stud Earrings",
    "site:otterbox.* Alpha Glass Screen Protector for Samsung Galaxy",
    "site:chezgagne.* The Foursome - Notepads 4 Pack",
    "site:shopbobbyk.* Art Print: Teal Drops",
    "site:shopdrt.* 3dRT Shirt",
    "site:surfsidesupply.* Ani Sleeveless Sweatshirt ‚Äì Pink Lavender",
    "site:shopwearwell.* The Elena - Very Wide",
    "site:decathlon.* Men's Jersey Merino GRVL900",
    "site:antisocialsocialclub.* ASSC DRAMATIC TEE L/S",
    "site:edyson.* Grant High Rise Flare Jeans",
    "site:organicbasics.* Core Full Coverage Bra",
    "site:futuresaint.* DRIVE and DESIRE T-Shirt",
    "site:symphonized.* USB C Headphones with Microphone",
    "site:twillory.* LEADER //¬†Extra Trim // Sleeve 36-37",
    "site:winxandblinx.* Princess Minky Baby Blanket",
    "site:princesspolly.* Besiana Mini Dress Low Impact",
    "site:orvis.* Men's Sunglove",
    "site:bandabags.* Tote Bag",
    "site:jupenyc.* Cooper Sweatshirt",
    "site:lonarc.* Bali One Piece Pistachio",
    "site:smartyhadaparty.* Disposable Plastic Dinnerware Value Set",
    "site:karmagifts.* Salt and Pepper Pinch Bowls",
    "site:jackieaslick.* Jacki Easlick Three Chickens Mesh Knit Sneakers - Men",
    "site:pumagolf.* Tech Crew Golf Socks",
    "site:risenjeans.* Undone Chic Straight Leg Jeans",
    "site:aleezaparis.* Harvert Top",
    "site:mirabellabeauty.* Mineral-based Anti-Aging HD Foundation",
    "site:trueclassic.* Fundamental Comfort Chino Pants 2-Pack",
    "site:ragcompany.* Loungewear Corduroy Pants",
    "site:princesspolly.* Popular Low Rise Mini Skirt Curve",
    "site:venturepal.* 64 Oz Motivational Water Bottle and Zero Sugar Electrolyte",
    "site:edikted.* Flutter Frilled Tie Back Top",
    "site:veracityselfcare.* Skincare Set",
    "site:gripjoy.* Women's Original Crew Non-Slip Socks - 3 Pack",
    "site:princesspolly.* Lex Top",
    "site:starfishproject.* Always Chic Gold Bar Necklace",
    "site:joyjolt.* Vacuum Insulated Tumbler With Lid & Handle",
    "site:adinaeden.* Pave Bar Accented Triple Overlap Open Bangle Bracelet",
    "site:edikted.* Katia V Neck Top",
    "site:noggiwear.* Pointelle Mauve + White  (2 Sets)",
    "site:vmelina.* Minimalist One Shoulder Top",
    "site:perfectdd.* Sports Bra & Short Set - XL",
    "site:doandbecollection.* PUFF SLEEVE SMOCKED WAIST ROMPER",
    "site:foreverylivingthing.* CONTRAST STITCHED SWEATPANT",
    "site:suzylevian.* Sterling Silver Cubic Zirconia Link Eternity Band Ring",
    "site:bewicked.* All Day Every Day Bodyshaper",
    "site:emprella.* Emprella Tank Tops for Women, 100% Cotton Ribbed Racerback Tanks for Casual, Lounging, and Sports",
    "site:ellesse.* Men's Zalenti T-Shirt - Off White",
    "site:htnnaturally.* Ubiquinol CoQ10 (Kaneka¬Æ) 100mg",
    "site:karmagifts.* Holiday Tea Towel",
    "site:agolde.* Poppy Tank in Black",
    "site:Flip.* Boho Scallop Lace Trim Detailed Button Down Solid Subtle Textured Slit Side Overlay Layered Cami Top",
    "site:thexbands.* Set of 5 Resistance Loop Workout Bands",
    "site:bayeas.* High Waisted Distressed Shorts",
    "site:itouchwearables.* ITouch Air 4 Smartwatch",
    "site:napahomeandgarden.* Hare'S Foot Fern Potted",
    "site:prettybirdjewelry.* V Shape Bezel Set 18k Rose Gold Plated Stacking Band Ring",
    "site:napahomeandgarden.* Almeta Jar",
    "site:sendaathletics.* Men's Ushuaia Pro 2.0 Futsal Shoe",
    "site:dreamlandbabyco.* Toddler Bamboo Pajamas",
    "site:princesspolly.* Alto Platform Heels Matte White",
    "site:evercado.* Rolling Stones Graphic Oversize Tee",
    "site:ridesnowboards.* CL-6 Snowboard Bindings Women's 2024",
    "site:yearandday.* The Essentials Set | Polished Steel",
    "site:thriftsthreads.* ALA√èA PANTS + TOP",
    "site:rta.* SHAY SHIRT",
    "site:antisocialsocialclub.* ASSC NIHON HOOD- BLACK",
    "site:conair.* BabylissPRO Nano Titanium Professional Hair Curler Machine, Miracurl 3 in 1 Tool for Tight, Loose or Wavy Curls",
    "site:protoarc.* RoyalAxe Y98 Mechanical Keyboard",
    "site:mnml.* Tricot Side Stripe Pants - Mauve",
    "site:sassywoof.* Dog Bundle - Pie There! - XXLarge Harness",
    "site:iconiclondoninc.* Hypnotise Them Gift Set - 2CT",
    "site:suzylevian.* Sterling Silver Cubic Zirconia Round U-Shape Eternity Band",
    "site:ragnco.* Edyta Ankle Strap Block Heel Sandals",
    "site:blomus.* KUMI Stoneware Creamer",
    "site:livdapparel.* Pleated Cowl Neck Top",
    "site:alepel.* Specialty Centerpieces",
    "site:threadedpear.* Sara Courier",
    "site:edyson.* Olivier High Rise Straight Jeans",
    "site:sabavihome.* Caesarea Elegant Wine Glass, Set of 6",
    "site:gripjoy.* Grip Socks for Toddlers & Kids - 2 Pack",
    "site:waterdalecollection.* Zemiros Bencher",
    "site:justbee.* Hinoki Sanctuary - Candles",
    "site:wilmax.* Set of 24 Round Porcelain White Soy Dish | 3",
    "site:fridasjewels.* Sterling Silver Oval Cut Gemstone Stud Earrings - 5 Options",
    "site:fellowproducts.* Carter Move Mug",
    "site:frenchkyss.* Braided Mock Neck Ribbed Sleeve Top",
    "site:getcasely.* Of Quartz! | Sculpted Marble Samsung Case",
    "site:beverlyrug.* Washable Non-Slip Pattern Area Rug Multicolor Tunnel",
    "site:en-masse.* Waxed Canvas Fly Wallet for Fly Fishing",
    "site:cozyearth.* Premium Plush Hand Towels",
    "site:legavenue.* Love Affair Lace Robe & Teddy Set",
    "site:avenuezoe.* Sunflower Stud Acetate Dangling Earrings",
    "site:mylesapparel.* Weekend Thermal Crew in Dark Khaki",
    "site:4artworks.* Peace Sign Hand Silhouette",
    "site:pmdbeauty.* PMD Clean for Teens",
    "site:wilson.* NXT Power String",
    "site:trulycontagio.* Comfy Infinity Scarf",
    "site:yomtovsettings.* Classic Clear & Black Rim Design Plastic Bowls | 40 Count",
    "site:hushlifeboutique.* Hush Shortsleeve Hoodie",
    "site:benbenapparel.* Girls Onesie Colorful Bathing Suit",
    "site:robertovino.* Milano RV Hoodie",
    "site:beatrizball.* Sierra Modern Rattan  8 X 10 Gold Frame",
    "site:noenddenim.* Selma Loose Straight Japanese Selvedge Denim Jeans",
    "site:shopmsinger.* LOGAN POPOVER HOODIE",
    "site:becketandquill.* Curb Link Necklace",
    "site:edikted.* Gingham Boxer Shorts",
    "site:trueclassic.* Navy Waffle Hoodie",
    "site:jetboil.* Pot Support",
    "site:princesspolly.* Cophen Top",
    "site:foreverylivingthing.* Polar Fleece Rec Hoodie",
    "site:elemis.* Pro-Collagen Rose Micro Serum",
    "site:kloudbambu.* Muslin Swaddle Floral Blanket, Buttery Soft, Lightweight, Breathable, Beautiful Vibrant Flower ",
    "site:shoporangefarm.* Organza Puff Sleeve Top",
    "site:raeliv.* Bead and Pearl Embellished Long Sleeves Mesh Top",
    "site:livdapparel.* Spaghetti Strap Tie Dye Midi Dress",
    "site:lippyclip.* Muted Hearts Lip Balm Holder",
    "site:princesspolly.* Rehna Top Lilac",
    "site:doralarsen.* ARALIE LACE TRIM SOFT BRA",
    "site:getautside.* Autside X Criquet Players - White / Paprika",
    "site:julielindh.* GLOW SKIN POTION Non-Tinted",
    "site:btiff.* RG223W B.Tiff 4-Stone Wide Ring",
    "site:edikted.* Monroe Micro Shorts",
    "site:snappower.* GuideLight 2 PLUS - Duplex",
    "site:objectshq.* Gold Statement Charger",
    "site:clawmoney.* Nuggets Sunglasses",
    "site:princesspolly.* Penney Mini Dress Lower Impact",
    "site:lovekinship.* Brightening Routine",
    "site:larktale.* Caravan V3 Stroller/Wagon",
    "site:nodny.* Cropped Pleated Dress",
    "site:serenelifehome.* Ultralight Sleeping Pad With Bag",
    "site:ellesse.* Women's Ilena Sweatshirt - Light Pink",
    "site:fashiongo.* Sexy Bow Tie Top",
    "site:trueclassic.* Heather Navy Active Crew Neck T-Shirt",
    "site:mbare.* Black Flat Lid Basket - Large",
    "site:zwilling.* AluPro Ceramic Aluminum Nonstick Fry Pan",
    "site:princesspolly.* Tavison Lace Top",
    "site:friendlyblues.* Signature Comfort - Straight Inseam 30",
    "site:loomini.* Cousin DIY 3 White Wood Letter - R",
    "site:nutrichefkitchen.* Cookware for Every Meal: Stainless Steel Cookware Stockpot 14 Qt",
    "site:bossmanbrand.* Bossman Relaxing Beard Balm - Beard Tamer, Relaxer, Thickener and Softener Cream - Beard Care Product - Made in USA",
    "site:salomon.* Abstract Snowboard 2024",
    "site:misen.* Mixing Spatula",
    "site:shopatkon.* Men's French Terry Dolman Tee",
    "site:getcasely.* Van Gogh's Flowers | 50th Anniversary Case - Bold + MagSafe¬Æ",
    "site:mixhers.* Herthrive (Original)",
    "site:estella-nyc.* Sun, Moon, and Stars Baby Onesies and Gifts Set",
    "site:emandlivjewels.* The Halley Huggies",
    "site:altfragrances.* Forbidden Fruit",
    "site:walooproducts.* Dual Slot CC Case",
    "site:lonarc.* Amatista One Piece (Latin)",
    "site:worldmoderndesign.* Frost Chandelier",
    "site:babsandbirdie.* The Sailor | Zippered Crossbody Bag (Camel) - Pick Your Strap ",
    "site:estella-nyc.* Organic Baby Gift Set | Food Onesie & Rattle",
    "site:jonathany.* Haze Solid Low-pile Area Rug - Round",
    "site:walooproducts.* Magnetic Mesh Band",
    "site:brumate.* Hopsulator Juggernaut | 24/25oz Cans",
    "site:avenuezoe.* Wide Leg Loose Pants",
    "site:princesspolly.* Hailey Strapless Mini Dress ",
    "site:fromourplace.* Better Bowl Set",
    "site:camilson.* Bohemian Outdoor Rug Brown",
    "site:candidaura.* Taking A Break Baseball Cap",
    "site:agolde.* Shoreditch Ski Club x Edie Leather Puffer in Graphite",
    "site:tinyrituals.* Blue Tiger Eye Stone Set",
    "site:edikted.* Pointelle Tank Top",
    "site:incipio.* Incipio Duo Case for Apple IPhone 14 / 13",
    "site:aleezaparis.* Peru Zipper Dress",
    "site:mia-bijoux.* Promise Ring ",
    "site:karmagifts.* Tank Top",
    "site:callowaymills.* This Is Us Doormat",
    "site:shopatlasgrey.* Oversized Bamboo T-Shirt",
    "site:anna-kaci.* Bell Bottom High Waist Denim Jeans",
    "site:zwilling.* ZWILLING Spirit 3-Ply Stainless Steel Ceramic Nonstick Saucepan",
    "site:alpcour.* Reclining Stadium Seat with Storage Pocket",
    "site:oliveandivorywholesale.* Gildan Unisex Sweatshirt",
    "site:sagebrookhome.* Sagebrook Home Neutral Textured Chevron Ceramic Planter with Contemporary Design Wooden Stand Indoor/Outdoor",
    "site:santandabel.* Women's Martinique¬Æ Banana Leaf Boxer Shorts",
    "site:hyfve.* Days Together Pointelle Sweater Cardigan",
    "site:btiff.* B.Tiff Princess Cut Tennis Bracelet",
    "site:princesspolly.* Calianna Pleated Mini Skort Camel",
    "site:thelovery.* Turquoise Lace Clover Stud Earrings",
    "site:casadilumo.* Infinity Pyramid",
    "site:bandier.* Run the City Baby Tee - White/Navy Blazer",
    "site:sundayswagger.* Maldives - Men's",
    "site:caskata.* Hawthorne Onyx Gold & Platinum Bread & Butter Plate",
    "site:ailiscorner.* Boho Key Ring Bracelet",
    "site:illestbrand.* Illest Bold Logo Black Tee",
    "site:pixiemood.* Caitlin Tote Small made with Recycled Bottles",
    "site:yoursuper.* Mugs",
    "site:kinflyte.* Freedom Bra Midi - Eco Jersey",
    "site:justbee.* Hinoki Sanctuary - Candles",
    "site:luvmyjewelry.* Aim High Open Triangle Diamond Ring in 14K White Gold",
    "site:feltandfat.* Espresso Cup in Milk",
    "site:1people.* Okayama OKJ - Workout Top - Opal",
    "site:messermeister.* Oliva Elite Kullens Santoku Knife 7 Inch",
    "site:hue.* Women's Ultra Soft High Waist Denim Leggings",
    "site:emprella.* Junior Softstyle Colorful Cotton Racerback Tank Top",
    "site:volkl.* Volkl V-Cell 10 320g Racquet Unstrung",
    "site:daniel-patrick.* Polar Fleece Roaming Sweatpants",
    "site:bandofthewild.* Ivory Bunny Costume - Hat + Tail",
    "site:vitalessentialsraw.* Grain-Free Duck Entr√©e Mini Nibs Freeze-Dried Dog Food - 25 Oz",
    "site:somethingglitter.* 0.06 ct Diamond tw and 12 1/10 ct TGW Created white sapphire set with chain silver",
    "site:ugearsmodels.* UGears Hexapod Explorer",
    "site:portlandaproncompany.* PAC Linen Tea Towels",
    "site:sijohome.* LuxeWeave Linen Duvet Cover",
    "site:elementalbottles.* Iconic  Charm Bottle",
    "site:ellesse.* Unisex Salino Track Pant - Navy",
    "site:shwallyhome.* The Romper",
    "site:astoria-activewear.* Seamless Ribbed Series Short",
    "site:losano.* EcoBliss Grace Top, Rib Knit, Breathable",
    "site:flip.* Off Shoulder Leopard Dress",
    "site:dreamfarm.* Ortwo Pepper & Spice Mill",
    "site:fashiongo.* Denim Jacket",
    "site:izakov.* 14K Gold Bezel Diamonds Drop Station Necklace",
    "site:stepone.* Boxer Brief Fly - Stocking Stuffers",
    "site:touchcat.* 'Tote-Tails' Designer Airline Approved Collapsible Cat Carrier",
    "site:dearjohndenim.* Lola Oversized Button-Down Boyfriend Shirt | Solid Blue",
    "site:paperplane.* Dream Lab Sweatshirt",
    "site:theloomia.* Melika Turkish Cotton Striped Terry Towel",
    "site:nossacoffee.* Mathilde's French Roast Ground Coarse - French Press",
    "site:findmenowthelabel.* Ross Panty",
    "site:rab.* Women's Kinetic 2.0 Waterproof Jacket",
    "site:wilmax.* Large White Tureen | 95 Oz",
    "site:farbank.* Rio Freshwater Trout Series Premier Rio Gold Fly Line",
    "site:doebeauty.* Doe Coloured Contact Lens - 10 Pack",
    "site:jackieaslick.* Butterfly Men's High-Top Leather Sneakers",
    "site:adinaeden.* Front Back Chandelier Fringe Drop Stud Erring",
    "site:jackieaslick.* Cardigan Thick Thread Turtleneck Pullover",
    "site:lonarc.* Arce Top",
    "site:somethingglitter.* 1 3/4ct Dew emerald cut created moissanite solitaire ring in 10k white gold",
    "site:vervetdenim.* Distressed Roll Up Stretch Mom Jeans",
    "site:fashiongo.* Fashion Ring Tassel Flap Crossbody Satchel",
    "site:refinerynumberone.* Aries Zodiac, Astrology, Horoscope Sweatshirt",
    "site:ezpzfun.* Tiny Placemat",
    "site:doucce.* Lovestruck Matte Liquid Lipstick",
    "site:princesspolly.* Caraway Pants",
    "site:viviencefol.* Gold Plated Diffuser, White Flower Scent",
    "site:instagram.* Fluffy Indoor Slippers",
    "site:threesixty6.* Men's Heathered Two-Tone Golf Polo",
    "site:uvebeauty.* Pro Antimicrobial Pencil Brush U09",
    "site:polclothing.* Metal Fringe Detailed French Terry Top",
    "site:marigoldshadows.* Zend Pleated Wrist Cuffs",
    "site:aleezaparis.* Argamini - Longer",
    "site:shopatkon.* Women's Ruffle Bell Sleeve Shirt Blouse",
    "site:portolano.* LADIES CASHMERE HAT COLORBLOCK",
    "site:revocoolers.* REVO Party Barge Cooler | Pink Coral | Insulated Beverage Tub by REVO COOLERS, LLC",
    "site:princesspolly.* Cammie Knit Set",
    "site:yeti.* Chews",
    "site:perfectdd.* V-Neck Sweatshirt & Short Set - Extra Small Top",
    "site:blomus.* STAY Outdoor Cushions",
    "site:basicbae.* Full Size Round Neck Slim Tank",
    "site:garmin.* Garmin Instinct 2/2s GPS Watch - Standard",
    "site:polychromegoods.* Life is Pain (au chocolat) Baby Onesie",
    "site:ellabonna.* Non-Slip Sole Baby Booties",
    "site:melodyehsani.* ME. Denim Shirt",
    "site:seerosego.* Multitasker Pant - Oxford Navy",
    "site:jackieaslick.* Jacki Easlick Poppy Print Classic Low-Top Canvas Shoes - Women's",
    "site:getcasely.* Hi, I'm the Party | Bachelorette Case - Essential + MagSafe¬Æ",
    "site:broilkingbbq.* Deluxe Stainless Steel Basting Set",
    "site:italic.* Heavyweight Crewneck Sweatshirt",
    "site:worldmoderndesign.* Eiffel Chair With Steel Legs",
    "site:fashiongo.* Cinco De Mayo Mexico Party Graphic T Shirts",
    "site:getcasely.* The Valentine's Collection | Red Painted Hearts Case - Essential",
    "site:dcshoes.* Men's Banshee Snowboard Pants",
    "site:1people.* Funchal Asymmetric Wrap Dress Black",
    "site:avenuezoe.* CZ Numbers Stud Earrings",
    "site:princesspolly.* Zahara Mini Dress - Petite",
    "site:shopatkon.* Konus Men's Cut Block Fishtail Tee in Black",
    "site:lonarc.* Katarsis Top",
    "site:shezza.* Crew Sock Bundles - 6-pack",
    "site:hausandhues.* Lion motivational (Unframed)",
    "site:dreamlandbabyco.* Toddler Bamboo Pajamas",
    "site:goat.* Gap Engineered by Balenciaga Dove No Seam Tee",
    "site:shopwearwell.* The Camila - Narrow",
    "site:instagram.* Floral Angel Sleeve Front Tie Maxi Dress",
    "site:petlife.* Luxe 'Paw Dropping' Designer Gray-Scale Tiger Pattern Mink Fur Dog Coat",
]